### ISSUE TITLE
Mapping rules are not correctly matched when plus or parenthesis are used in the mapping rules

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/APIcast#1001]
Mapping rules are not correctly matched when plus or parenthesis are used in the mapping rules

##### Version

I'm using the hosted APIcast (SaaS). 

##### Steps To Reproduce

1. Define two mapping rules:

- /api-A/say-hello+$
- /api-B/say-hello(test)$

2. Try to query the API with:

```sh
curl https://blablabla/api-A/say-hello+
curl https://blablabla/api-A/say-hello
curl https://blablabla/api-A/say-hellooooo
curl https://blablabla/api-B/say-hello(test)
curl https://blablabla/api-B/say-hellotest
```

##### Current Result

- `curl https://blablabla/api-A/say-hello+` => 404 No mapping rules matched
- `curl https://blablabla/api-A/say-hello` => 200
- `curl https://blablabla/api-A/say-hellooooo` => 200
- `curl https://blablabla/api-B/say-hello(test)` => 404 No mapping rules matched
- `curl https://blablabla/api-B/say-hellotest` => 200

##### Expected Result

- `curl https://blablabla/api-A/say-hello+` => 200
- `curl https://blablabla/api-A/say-hello` => 404 No mapping rules matched
- `curl https://blablabla/api-A/say-hellooooo` => 404 No mapping rules matched
- `curl https://blablabla/api-B/say-hello(test)` => 200
- `curl https://blablabla/api-B/say-hellotest` => 404 No mapping rules matched

**Comment by eloycoto** [comment]
Tested this with the following configuration, the main issue, regexp need to be scaped if you want to match they literal. 

Config: 
```
{
  "services": [
    {
      "id": 42,
      "backend_version": 1,
      "backend_authentication_type": "service_token",
      "backend_authentication_value": "token-value",
      "proxy": {
        "api_backend": "https://echo-api.3scale.net",
        "proxy_rules": [
          {
            "pattern": "/hello\\+$",
            "http_method": "GET",
            "metric_system_name": "hits",
            "delta": 1
          },
          {
            "pattern": "/hello\\(test\\)$",
            "http_method": "GET",
            "metric_system_name": "hits",
            "delta": 1
          },
          {
            "pattern": "/mytest$",
            "http_method": "GET",
            "metric_system_name": "hits",
            "delta": 1
          }
        ],
        "policy_chain": [
          {
            "name": "apicast.policy.apicast"
          }
        ]
      }
    }
  ]
}
```

Curl calls:
```
bash-4.2$ curl "http://localhost:8080/hello+?user_key=123"  -s -w '%{http_code}\n' -o /dev/null
200
bash-4.2$ curl "http://localhost:8080/hello++?user_key=123"  -s -w '%{http_code}\n' -o /dev/null
404
bash-4.2$ curl "http://localhost:8080/hello(test)?user_key=123"  -s -w '%{http_code}\n' -o /dev/null
200
bash-4.2$ curl "http://localhost:8080/hello(test)+?user_key=123"  -s -w '%{http_code}\n' -o /dev/null
404
bash-4.2$
```
