### ISSUE TITLE
OAuth 2.0 Mutual TLS Client Authentication and Certificate-Bound Access Tokens

### ISSUE THREAD

**Issue by mikz** [3scale/APIcast#1003]
We would like to implement support for https://tools.ietf.org/html/draft-ietf-oauth-mtls.

This should be a requirement for PSD2 support.

**Comment by y-tabata** [comment]
Hi,
I'm trying to create a new policy for OAuth 2.0 MTLS Client Authentication.
This policy is  based on https://tools.ietf.org/html/draft-ietf-oauth-mtls, and checks the digest of client certificate equals to the cnf claim in the access token.

I'd like to get some idea for the integration test which can test the apicast policy with a client certificate.
