### ISSUE TITLE
Make the JWT claim to get client_id configurable [THREESCALE-2264]

### ISSUE THREAD

**Issue by mikz** [3scale/APIcast#1008]
Various IDPs store the client_id in different claims of the JWT.
We need to make this configurable, so we can be compatible with different IDPs.

Options include:
* hardcoded claim name
* liquid templating

**Comment by davidor** [comment]
Do you think liquid templating is needed? Any example of liquid expression that could be helpful in this case?

**Comment by mikz** [comment]
I'd imagine those from the top of my head:

* get the first element of an array (`aud | first`)
* get Nth element of an array (`aud[3]`)
* fall through several values if empty (`azp | default: appid | default: ...`)

**Comment by davidor** [comment]
:+1:
