### ISSUE TITLE
Ensure lock is released in the ConfigurationLoader module

### ISSUE THREAD

**Issue by davidor** [3scale/APIcast#1010]
When downloading the configuration from Porta, we use an `ngx.semaphore` to make sure that there are not several requests at the same time trying to download the same configuration and storing it in memory.

Here's the code function that does that:
https://github.com/3scale/APIcast/blob/6f6aeb034e0c388c9280c6e259f4ff9303be859f/gateway/src/apicast/configuration_loader.lua#L199

The problem is that if there's an error while trying to download the config, the thread dies and the lock is never returned. Subsequent requests that try to download the config for the same service will wait for 15 s and then fail because they will not be able to acquire the lock (it was never returned in the first call). There's a bug reported when this happened:  https://issues.jboss.org/browse/THREESCALE-2194

My first thought was to just wrap that code on an xpcall or pcall. However, I think that we should implement a generic "finally/ensure" clause because we have the same pattern in different parts of the code. For example: https://github.com/3scale/APIcast/blob/e9c8f0a59318fa4f37e9fa41422cce5d046a92ff/gateway/src/apicast/policy/3scale_batcher/3scale_batcher.lua#L112

**Comment by mikz** [comment]
I think we could try it with some primitives of https://github.com/3scale/APIcast/tree/master/gateway/src/resty/concurrent and maybe even prove they are "safe". Do you see any pattern in concurrent-ruby that would match this?

**Comment by davidor** [comment]
There are several possible solutions.

To start with, I think that we could change the ["resty.synchronization" module](https://github.com/3scale/APIcast/blob/master/gateway/src/resty/synchronization.lua) to expose a method that ensures that the lock is always released.

Something like this:

```lua
function _M:sync(key, timeout, task)
  local sema = self:acquire(key)

  local ok, err = sema:wait(timeout)

  if ok then
    -- safely run task(). Using the SafeTaskExecutor 
    self:release(key)
    sema:post()
  end

end
```

**Comment by mikz** [comment]
@davidor My point was more about naming than the implementation. I'd try to find a proper abstraction name in concurrent-ruby. And it also makes it easier to check for edge cases, by checking the source code.

I think some of the thread pool executors implements this (a limit of parallel executors and a timeout).
Kind of like https://github.com/3scale/APIcast/blob/master/gateway/src/resty/concurrent/timer_pool_executor.lua but not using timers but threads for example.

**Comment by davidor** [comment]
Sorry @mikz , I forgot to answer this.

I think we just need something similar to Ruby's `Mutex.synchronize`. Something that takes care both of acquiring and releasing the lock so the user of the method does not have to. Similar to the method I wrote in my previous comment. The difference is the `key` param.
