### ISSUE TITLE
Investigate delegation of upstream call via http proxy

### ISSUE THREAD

**Issue by mikz** [3scale/APIcast#1016]
It would be an interesting use case to send some requests to upstream through an http proxy enabled by policy.

The HTTP proxy could do the following:

* apply Fuse transformations
* content caching

Would be great to have an analysis of how this can be implemented and if using HTTP Proxy is feasible and how to work around TLS traffic.

**Comment by eloycoto** [comment]
Fixed by https://github.com/3scale/APIcast/pull/1080
