### ISSUE TITLE
use opm instead of luarocks

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#104]
Luarocks is trouble. It needs to be installed with proper settings. Passed proper flags.

We can use soon to be released openresty package manager [opm](https://github.com/openresty/opm).

**Comment by rnc** [comment]
I thought we had discussed using a standard build of luarocks rpm?

**Comment by mikz** [comment]
Yes. Right now that is the approach we will follow. But luarocks has issues and in the future would be great to drop it. `opm` will be part of the standard openresty distribution, so it would be less dependencies.

**Comment by rnc** [comment]
@mikz Internally we are not using any particular paths or building it (as per the jira I entered for changes upstream).

**Comment by mikz** [comment]
Yes. Understood. 

Still luarocks causes issues for local development. opm is in still very early stage, so it will take to mature. luarocks will surely stay for some time.

**Comment by davidor** [comment]
We are using [lua-rover](https://github.com/3scale/lua-rover) now. Closing this.
