### ISSUE TITLE
Need Access to download docker image quay.io/3scale/docker:ci-2.3.1-3

### ISSUE THREAD

**Issue by chavdam** [3scale/APIcast#1046]
I wanted to setup 3Scale API Management portal on my local machine. When I tried to build the docker image from the following source : 

https://github.com/3scale/porta

I got this error:

```
SBK132981MAC1:porta chavdam$ docker build .
Sending build context to Docker daemon  37.22MB
Step 1/16 : FROM quay.io/3scale/docker:ci-2.3.1-3
unauthorized: access to the requested resource is not authorized
```

Could you please help me with this ?

**Comment by davidor** [comment]
Hi @chavdam ,

It's an issue in [Porta](https://github.com/3scale/porta). They use JIRA instead of github issues. Here's the link: https://issues.jboss.org/browse/THREESCALE-2609

**Comment by chavdam** [comment]
👍
