### ISSUE TITLE
nauthorized: access to the requested docker:ci

### ISSUE THREAD

**Issue by sarikav1986** [3scale/APIcast#1055]
I am trying to setup 3Scale API Management portal on my local machine. When I tried to build the docker image from the following source :

https://github.com/3scale/porta

Looks like docker:ci-2.3.1-3 image needs credentials. 

I got below error:

/Library/Developer/CommandLineTools/usr/bin/make test-run tmp-export --keep-going
/Users/vermap/hackathon/porta/.bin/docker-compose up --remove-orphans -d cache || /Library/Developer/CommandLineTools/usr/bin/make clean-cache cache
Building cache
Step 1/16 : FROM quay.io/3scale/docker:ci-2.3.1-3
ERROR: Service 'cache' failed to build: unauthorized: access to the requested resource is not authorized
/Library/Developer/CommandLineTools/usr/bin/make clean

**Comment by VinayBhalerao** [comment]
Hi @sarikav1986,

The issue is already reported here https://issues.jboss.org/browse/THREESCALE-2609. You can monitor the progress by subscribing to the updates.
