### ISSUE TITLE
BACKEND_ENDPOINT_OVERRIDE parameter has an incorrect description

### ISSUE THREAD

**Issue by avilatusell** [3scale/APIcast#1059]
The description of [BACKEND_ENDPOINT_OVERRIDE](https://github.com/3scale/APIcast/blob/v3.5.0/doc/parameters.md#backend_endpoint_override) states that this environment variable is `Useful when deploying outside OpenShift deployed AMP`. Currently the value is already set to the route of backend-listener so the environment variable is no longer required when deploying APIcast outside the 3scale project. This has also been reported in [THREESCALE-2462](https://issues.jboss.org/browse/THREESCALE-2462).

However, when deploying APIcast in the another project but in the same OpenShift cluster that contains 3scale API Manager, BACKEND_ENDPOINT_OVERRIDE can be used to override the public route for backend-listener and set it to the OpsneShift backend-listener service address.

**Comment by mikz** [comment]
It used to be the case. But then we switched the logic entirely and now it is useful when deploying inside the same cluster, so it can be used to use internal service over external Route.

**Comment by davidor** [comment]
Fixed in #1063
