### ISSUE TITLE
Feature: more logging variables available for the access log

### ISSUE THREAD

**Issue by magnusvage** [3scale/APIcast#1082]
At the moment, the log format of the access log in APICast is the following:

https://github.com/3scale/APIcast/blob/bfa3ac9be38c99da5c01cfba4becd0688513b0fe/gateway/http.d/apicast.conf.liquid#L1

There is a variable there called $post_action_impact, which is a variable created by the APICast Lua extensions. It would be great if more variables are set, so that I can set up a log format most suitable for me. Right now, the use case would be to see which service was called, and which method of that service. With that data, working with the logs in ELK or similar would become much easier (filtering on service  and method names instead of paths matching a particular regex etc.)

The change could be completely backwards compatible by just making the variables available but leaving the default logging format as it is.

**Comment by eloycoto** [comment]
Hi @magnusvage 

Some work has been done over the last weeks to address this, I'll keep you posted in the following days. 

Regards.

**Comment by magnusvage** [comment]
@eloycoto great news! Look forward to seeing the results :)

**Comment by eloycoto** [comment]
Hi @magnusvage 

I sent the PR, need to be reviewed, but mostly address your behaviour, the example policy configuration will be something like this: 

```
{
  "name": "apicast.policy.logging",
  "configuration": {
    "enable_access_logs": false,
    "custom_logging": "[{{time_local}}] {{host}}:{{server_port}} {{remote_addr}}:{{remote_port}} \"{{request}}\" {{status}} {{body_bytes_sent}} ({{request_time}}) {{post_action_impact}}",
  }
}
```
This is the PR:  
https://github.com/3scale/APIcast/pull/1089

I will love your input here, and be able to provide to you the right solution that fixes your use case. :-)

**Comment by magnusvage** [comment]
Hi @eloycoto 

Looks good!

So, this policy would completely override the access log format set at the NGINX level? And without this policy on a service, the access logs would be formatted according to the configured NGINX format?

My biggest concern here is that we would in our case consume the access logs with Logstash, and we would need a predictable format so that our parsing pipeline can parse every line of the access log, regardless of whether the new policy is there or not. Therefore I was hoping to be able to control the logging format at the gateway level. If (for example) the 3scale base policy set a bunch of variables (basically everything you could think of), then we could pick and choose from them in the nginx.conf and every log entry would look exactly the same.

Perhaps this is achievable with the policy approach as well? Can I bulk add/change policies on all services within a given 3scale domain?

**Comment by eloycoto** [comment]
Hi @magnusvage 

I'll think about your use case

Thanks

**Comment by magnusvage** [comment]
@eloycoto thanks

The only important thing is that every access log row is parseable with the same logic, regardless of the configuration applied to any services. That could very well be achieved in a policy approach, but then I think that the custom logging info configured in the policy would have to be placed within some sort of delimiters in the access log row. Example:

log_format time '[$time_local] $host:$server_port $remote_addr:$remote_port "$request" $status $body_bytes_sent ($request_time) $post_action_impact <$custom_logging_policy_data>';

Then we could parse everything within the <> as a single entity.

But, then we wouldn't be able to parse the inside of the <>, since that format would be a service specific string. If we wanted to visualise the logs of a single service (or even a single method within a service), then we would have to know where to get the method name from the log row, every time.

**Comment by eloycoto** [comment]
Hi @magnusvage 

We have some discussion about your proposal in the PR#1089. New changes will be addressed this week. 

Thanks.

**Comment by magnusvage** [comment]
@eloycoto I'm still investigating the upstream_response_time.

One other thing: {{host}} used to become the APICast hostname with the old log format, but now with the custom logging we see the backend hostname here instead. Should we use some other variable names to get the APICast value again?

**Comment by eloycoto** [comment]
Hi @magnusvage 

Good catch, I made some changes in the code and a PR is already open. I'll try to get this in the new stable release. 

https://github.com/3scale/APIcast/pull/1116

Regards

**Comment by magnusvage** [comment]
@eloycoto do you have any suggestions on how we can get information into the access log identifying the consumer? Application identifier, identifier of the account owning the application or something along those lines?

**Comment by eloycoto** [comment]
Hi @magnusvage what information do you want? The only information that I can think that can be provided is the number of metrics that were increment. Oher information belongs to different components. 

Regards.

**Comment by magnusvage** [comment]
@eloycoto we want the log entry to reflect which application made the call to the API. Application name (and preferably also application plan system name) would be perfect. I know that information is not stored in the spec.json configuration used by the gateway, so the only way I can think of is that, when APICast makes the auth/authrep call to the 3scale backend to authenticate the call, the response from the backend contains these pieces of information, which we then could put into the log entry using the custom logging policy.

**Comment by magnusvage** [comment]
Hi @eloycoto , is it possible to log the mapping rule that matched? We want to group log entries based on endpoints, and if the path contains path variables an access log entry containing /get/variable1 and /get/variable2 will be hard to match. But, if we could log "mappingrule: /get/{pathVariable}" or something similar, it would be a breeze to do analytics based on endpoints.

**Comment by magnusvage** [comment]
Hi @eloycoto we are still seeing the host name bug (backend host name instead of gateway host name) in the logs. Using image quay.io/3scale/apicast:v3.7.0. Did the fix make it into the release?

**Comment by eloycoto** [comment]
could you share your config?
Regards

**Comment by magnusvage** [comment]
```
local logging_policy_config = cjson.decode([[
    {
      "enable_access_logs": false,
      "custom_logging": "[{{time_iso8601}}] [{{req.headers.X-Forwarded-For}}] {{host}}:{{server_port}} {{remote_addr}}:{{remote_port}} \"{{request}}\" {{status}} {{body_bytes_sent}} ({{request_time}}) ({{upstream_response_time}}) {{post_action_impact}} {{service.id}} {{service.system_name}}"
    }
]])
```    
produces the log entry
`[2019-12-18T08:54:25+00:00] [<REDACTED>] echo-api.3scale.net:8080 <REDACTED>:10380 "GET /echo/3scale HTTP/1.1" 200 832 (0.292) (0.292) 0 <REDACTED> <REDACTED>`

echo-api.3scale.net is the backend host.

**Comment by eloycoto** [comment]
@magnusvage instead of `{{host}}:{{server_port}}`, please use: `{{original_request.host}}:{{server_port}}`

Regards

**Comment by magnusvage** [comment]
@eloycoto thanks, that solved it! Is this documented somewhere? Can't find the information on https://github.com/3scale/APIcast/tree/master/gateway/src/apicast/policy/logging
