### ISSUE TITLE
HTTP_X_3SCALE_PROXY_SECRET_TOKEN 

### ISSUE THREAD

**Issue by opensourceonly** [3scale/APIcast#1104]
[provide a description of the issue]
Per the feature, it says that "Enables you to block any direct developer requests to your API backend; each 3scale API gateway call to your API backend contains a request header called X-3scale-proxy-secret-token. The value of this header can be set by you here. It's up to you ensure your backend only allows calls with this secret header."

No HTTP_X_3SCALE_PROXY_SECRET_TOKEN is being added/created while using self-managed gateway deployed in Openshift to send the request to the backend.

##### Version
OpenShift Master:
v3.9.27
Kubernetes Master:
v1.9.1+a0ce1bc657
OpenShift Web Console:
v3.9.27

APICAST 
3scale-amp25/apicast-gateway
##### Steps To Reproduce

1. [step 1 (json configuration file, if applies)]
2. [step 2 (curl commands to reproduce, if applies)]
3. [step 3]

##### Current Result
Token not being created
##### Expected Result
Secret token
##### Additional Information

* [Gist with minimal reproducible configuration, see guidelines for contributing for details]
* [Gist with nginx log output]

**Comment by raghubanda** [comment]
@mikz Have you heard of this before as a known issue? I m not sure if it has to do something with the compatibility of openshift vs apicast version in this case

**Comment by mikz** [comment]
Can you point APIcast to https://echo-api.3scale.net and send a `curl -v` output?
