### ISSUE TITLE
Re-write rules determined by HTTP Verb

### ISSUE THREAD

**Issue by philogilvie1** [3scale/APIcast#1130]
As far as I can tell it isn't possible to create a URL re-write rule based on whether the HTTP verb is a GET, POST, etc. If I have a single endpoint for all verbs like _/api_ then I can't apply re-write rules if I want GET to have a different target to POST. Instead I have to create _/api/retrieve_ for GET and _/api/create_ for POST. The reason this is an issue is that the REST API for JBoss BPMS 6.4 & RHPAM 7.x has different endpoints for POST and DELETE (I know that this will change with the Kogito release, where domain-specific APIs are possible). There are doubtless other use cases where being able to apply re-write rules based on the verb - e.g. in CQRS a GET might go to Data Grid and a POST might go to a DBMS.

**Comment by mklan** [comment]
@philogilvie1 have you found a solution?
