### ISSUE TITLE
quay.io/3scale/apicast:master throws warn after pull complete

### ISSUE THREAD

**Issue by rajputvishwas** [3scale/APIcast#1131]
[provide a description of the issue]
Hi,
I am trying very simple command, assume that I have valid access token and admin portal domain.

docker run --name apicast --rm -p 8080:8080 -e THREESCALE_PORTAL_ENDPOINT=https://ACCESS_TOKEN@ADMIN_PORTAL_DOMAIN quay.io/3scale/apicast:master

##### Version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:53:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

docker inspect --format='{{.Created}}' quay.io/3scale/apicast:master
2019-10-17T09:30:58.986257318Z

##### Steps To Reproduce

1. You need to sign up to 3scale account.  [https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.0/html-single/deployment_options/index#apicast-overview]

2. docker run --name apicast --rm -p 8080:8080 -e THREESCALE_PORTAL_ENDPOINT=https://ACCESS_TOKEN@ADMIN_PORTAL_DOMAIN quay.io/3scale/apicast:master

##### Current Result
master: Pulling from 3scale/apicast
8ba884070f61: Pull complete 
5c7077850b1d: Pull complete 
955ea15d85ac: Pull complete 
d0f44c596870: Pull complete 
633094a2dec0: Pull complete 
1a777cd0f1ad: Pull complete 
e738616bccd8: Pull complete 
715d85ca0873: Pull complete 
ccfa3dfeebe9: Pull complete 
Digest: sha256:f8b6673c8b354749b9eb5bb6657a4d7e993e2ff421803f2586a5dd6b180db5b3
Status: Downloaded newer image for quay.io/3scale/apicast:master
2019/11/04 10:28:17 [warn] 16#16: *2 [lua] _G write guard:12: writing a global lua variable ('lfs') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7fc670b10980
	[C]: at 0x7fc6725e4b60
	[C]: in function 'pcall'
	./lua_modules/share/lua/5.1/pl/path.lua:22: in main chunk
	[C]: in function 'require'
	./src/apicast/cli/filesystem.lua:6: in main chunk
	[C]: in function 'require'
	./src/apicast/cli/template.lua:11: in main chunk
	[C]: in function 'require'
	./src/apicast/cli/command/start.lua:17: in main chunk
	[C]: in function 'require'
	./src/apicast/cli.lua:18: in function 'load_commands'
	./src/apicast/cli.lua:23: in main chunk
	[C]: in function 'require'
	/tmp/BV0ywKmDGJ:60: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>, context: ngx.timer
2019/11/04 10:28:17 [warn] 16#16: *2 [lua] _G write guard:12: writing a global lua variable ('yaml') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7fc6706fdd00
	[C]: in function 'require'
	./lua_modules/share/lua/5.1/lyaml/init.lua:34: in main chunk
	[C]: in function 'require'
	./src/resty/yaml.lua:6: in main chunk
	[C]: in function 'require'
	./src/apicast/configuration_loader/data_url.lua:9: in main chunk
	[C]: in function 'require'
	./src/apicast/configuration_loader.lua:5: in main chunk
	[C]: in function 'root_require'
	...
	[C]: in function 'require'
	./src/apicast/cli/command/start.lua:18: in main chunk
	[C]: in function 'require'
	./src/apicast/cli.lua:18: in function 'load_commands'
	./src/apicast/cli.lua:23: in main chunk
	[C]: in function 'require'
	/tmp/BV0ywKmDGJ:60: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>, context: ngx.timer
^C
root@pod-pod-AppModelPlatformTestingPhase4:~/okd# 
root@pod-pod-AppModelPlatformTestingPhase4:~/okd# docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:53:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

##### Expected Result
  It should pull and run the image

**Comment by keyur9** [comment]
+1. Having a similar error. 

Is there any way to resolve it?

**Comment by rajputvishwas** [comment]
I guess there is problem with the image quay.io/3scale/apicast:master, I have then switched to registry.access.redhat.com/3scale-amp20/apicast-gateway:1.0.

Follow the given steps

oc create secret generic apicast-configuration-url-secret --from-literal=password=https://208xxxxxxxxxxxxxxxxxxxxxxx0d6@xxxxx-admin.3scale.net --type=kubernetes.io/basic-auth    #Create secret for 3scale app 

oc new-app --docker-image=registry.access.redhat.com/3scale-amp20/apicast-gateway:1.0 --param CONFIGURATION_URL_SECRET=apicast-configuration-url-secret -e THREESCALE_PORTAL_ENDPOINT=https://208xxxxxxxxxxxxxxxxxxxxxxx0d6@xxxxx-admin.3scale.net #Create 3scale app

**Comment by keyur9** [comment]
Thank you for your help @rajputvishwas. The steps you'd shared works fine.
