### ISSUE TITLE
The server doesn't have a resource type "kind: Template, apiVersion: v1".

### ISSUE THREAD

**Issue by es02** [3scale/APIcast#1148]
The provided example YAML does not work for OpenShift Online.

##### Version

OpenShift Online - Current Version

##### Steps To Reproduce

1. Create new OpenShift Online project
2. Create new application and specify Import YAML
3. https://raw.githubusercontent.com/3scale/apicast/master/openshift/apicast-template.yml

##### Current Result
The server doesn't have a resource type "kind: Template, apiVersion: v1".

##### Expected Result
--> Creating resources with label app=3scale-gateway ...
    deploymentconfig "apicast" created
    service "apicast" created
--> Success
    Run 'oc status' to view your app.

**Comment by eloycoto** [comment]
Hi, 

Thanks for the issue, I'll fix the following days. 

I would recommend you to use the official 3scale templates:
https://github.com/3scale/3scale-amp-openshift-templates

Or use the APIcast from the operator hub.

https://operatorhub.io/operator/apicast-community-operator

Regards

**Comment by tkan145** [comment]
This is no longer valid.
