### ISSUE TITLE
Logging policy configuration sent to APICast with incorrect syntax

### ISSUE THREAD

**Issue by adeeyacoby10** [3scale/APIcast#1165]
[provide a description of the issue]
Hi,
We are running our 2scale system on version 2.7,
When we try to add the logging policy to our APICast we see in the logging that:
Failed to load policy: logging version: builtin err: /opt/app-root/src/src/apicast/policy/logging/loggign.lua:59: bad argument #1 to 'ipairs' (table expected, got nil), client: [ip_address], server: _, request: <request>, host: [host]
We checked the policy chain of the service and saw that the configuration of the logging policy contains the following field:
```json
"condition": {
   "combine_op":"and"
}
```
In a working policy we see:
```json
"condition": {
   "combine_op":"and",
   "operations":{}
}
```
In addition after manually removing the condition filed, the error does not happen any more. 

##### Steps To Reproduce

1. Add the logging policy
2. Add JSON object config
3. Enable JSON logs

**Comment by eloycoto** [comment]
Hi, 

I'm able to reproduce this issue, I'll have a look later today and I'll try to send a fix for 2.8 version that we'll release in the next couple of weeks. 

Regards
