### ISSUE TITLE
Add documentation to customize APIcast

### ISSUE THREAD

**Issue by vramosp** [3scale/apicast#120]
With the new modular architecture, it'd be good to create some documentation which explains how to add custom behavior to the gateway by creating a module.

cc @andrewdavidmackenzie

**Comment by mikz** [comment]
This is good use case for an example. We have `examples` folder with common customizations that people can execute.

**Comment by mikz** [comment]
Also how to add ssl https://github.com/3scale/apicast/pull/141 and how to build a docker image with customizations https://github.com/3scale/apicast/pull/144. Also making sample module in #140.
