### ISSUE TITLE
Create example OAuth2 integration

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#121]
We need an easy way to demo OAuth2 integration of APIcast. Not only demo, but to try in a browser after making changes to verify all works. 

##### Steps

1. create JSON configuration using example OAuth server
2. create html page using that configuration
3. write step by step guide to try whole flow

##### Expected Result

Everyone having the necessary software installed should be able to go through full OAuth flow on their local machine.

**Comment by mikz** [comment]
@mpguerra could you try to handle this? We have `examples` folder that is meant for this.

**Comment by mikz** [comment]
I guess the sooner the better, because when doing this we will discover edge cases and bugs in the implementation and will have to fix them.

**Comment by andrewdavidmackenzie** [comment]
We should probably talk to QE about testing OAuth flow in one of the next two (discussing, I think we added one for 3 iterations in total - TBD) iterations...

We should do it and remove any issues we find before then - which I'd estimate as Nov 24th maybe...

**Comment by andrewdavidmackenzie** [comment]
@mpguerra We are reviewing work required before the Candidate Release in 2 weeks - and OAuth is an important one. Will you be able to test / modify /confirm OAuth next week?

**Comment by mpguerra** [comment]
already on it :) see oauth-examples branch for progress so far. 
Planning to make some PRs between today and tomorrow

**Comment by andrewdavidmackenzie** [comment]
great, thanks.

**Comment by mayorova** [comment]
Closed by https://github.com/3scale/apicast/pull/150
