### ISSUE TITLE
add option to disable lua code cache and enable code/configuration reloading

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#124]
We need to have an option to disable lua code cache and enable code reloading.
That will also make configuration reloading work. Later we might need two different options.
One for code and second for configuration.

##### Version

[provide output of the `nginx -V` or `openresty -V` command from openshift/local terminal]
[provide timestamp of the docker image from `docker inspect --format='{{.Created}}' quay.io/3scale/apicast:v2` ]

##### Steps To Reproduce

1. `bin/apicast -C`
2. do a request 
3. change code and configuration
3. see configuration and code reloaded

##### Current Result

does not reload the configuration or code

##### Expected Result

should reload the configuration and code from filesystem/api

##### Additional Information

the `-C` option is just suggestion. can be something else.

**Comment by jmprusi** [comment]
perhaps we can use something that states is not meant for production, like:  --devel or -D  (debug, devel...)

**Comment by mikz** [comment]
We have `-q` and `-v` for decreasing/increasing verbosity level. Then there will have to be one for config reload and one for code reload I guess.

But I kind of like the idea of `--dev`.

**Comment by mikz** [comment]
I'll probably go with `-r` for reloading configuration and `--dev` for disabling code cache.

**Comment by mikz** [comment]
Turns out there is no cross platform way of getting long options. So i'll go with `-d` for development mode.

**Comment by mikz** [comment]
In the and #134 implements just the config reloading. Disabling lua code cache is too annoying to do.
