### ISSUE TITLE
Bake functionality into V2 that deals effectively with 3scale being unreachable

### ISSUE THREAD

**Issue by tnscorcoran** [3scale/apicast#126]
A production ready version of this:
https://support.3scale.net/codehub/use-prebuilt-cache

Should check the cache for dynamically added keys/tokens - rather than hard code them in whitelist.lua

Should avoid the long in-band wait associated with a 503 with the current solution. Background job?

**Comment by mikz** [comment]
We can use the previously cached response and not delete the cache when 3scale can't be reached.
But that feature has to be opt-in and have to be configured somehow. Or making it really easy to be a module. 

looping in @vramosp

**Comment by andrewdavidmackenzie** [comment]
Sounds like this needs a bit more discussion/definition and decision on how important it is to include in 2.0
