### ISSUE TITLE
I would like to make an api available on 3scale at a certain time.

### ISSUE THREAD

**Issue by fSantosLima** [3scale/APIcast#1274]
Hey guys!

is it possible to publish an api on 3scale and make it available only at a certain time of day? For example: from 9:00 am to 9:00 pm. I researched whether it would be possible with the available policies. But I didn't find anything about it. I thank the attention.

**Comment by eloycoto** [comment]
A custom policy is the best way, we didn't do this at all. 

Another option is the conditional policy + liquid filters to check time.
