### ISSUE TITLE
Redundant location block "client_secret_matches"

### ISSUE THREAD

**Issue by mpguerra** [3scale/apicast#129]
In apicast.conf there is a client_secret_matches location block that is not currently used or needed: 

https://github.com/3scale/apicast/blob/c306f49655caa6cae98479ff53fad41afd1b57ea/apicast/conf.d/apicast.conf#L121-L127

**Comment by andrewdavidmackenzie** [comment]
Thanks Pili.... keep polishing it!

**Comment by mikz** [comment]
Next time you can just edit it from github ;) Might be easier than creating an issue.

**Comment by mpguerra** [comment]
Thanks, I will next time, I was just shy about it ;)
