### ISSUE TITLE
Ability To send Custom Attribute to Internal Backends

### ISSUE THREAD

**Issue by abarrak** [3scale/APIcast#1290]
Hi Guys,

Is there an out of the box way to pass along or send info from API cast to backend APIs? 
This is so that the latter can recognize the origin (user). 

Specifically, In registration we have custom info attribute (numeric) added through Porta, and would like to pass/proxy it to backends in headers?

Any suggested solution? 
Thanks.

**Comment by es02** [comment]
You should be able to achieve this easily with the Header Modification Policy, adding the relevant fields in as liquid tags

https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.10/html/administering_the_api_gateway/apicast_policies#header_modification

**Comment by abarrak** [comment]
Hi @es02,

Thanks so much for the quick feedback!
Looking into it now.

Do I have access for the registration custom attributes in policies?

**Comment by es02** [comment]
I'm not 100% sure what you mean by tha, but you can check exactly what fields you have access to with the Liquid Debug Policy
https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.10/html/administering_the_api_gateway/apicast_policies#liquid_context_debug

**Comment by abarrak** [comment]
I meant [additional signup fields here](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.7/html/creating_the_developer_portal/custom-signup-fields).

**Comment by es02** [comment]
I believe so, but the Liquid Debug Policy will tell you for sure.

**Comment by abarrak** [comment]
Many thanks.
I guess this close the issue overall.
