### ISSUE TITLE
Support https in the OpenShift apicast template

### ISSUE THREAD

**Issue by radarlui** [3scale/APIcast#136]
There should be an OpenShift template for deploying the nginx gateway on OpenShift with a service supporting https. The key and certificate for the ssl config come from the volume of an OpenShift secret.

**Comment by mikz** [comment]
That would work only for one service. Gateway has to support multiple, so it has to use [`ssl_certificate_by_lua`](https://github.com/openresty/lua-nginx-module#ssl_certificate_by_lua_block) to find right certificate for the domain name.

**Comment by jmprusi** [comment]
**If we terminate the SSL at the router layer**, we can use a "Re-Encryption" route, the openshift router will validate the SSL cert based on the CA (not on host) and we don't need to do the SNI work right now.

This way we can have SSL everywhere.

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/routes.html#re-encryption-termination

**Comment by mikz** [comment]
This can be solved by #141.

**Comment by andrewdavidmackenzie** [comment]
Joaquim, can you tell us if that workaround will continue to be supported in OpenShift 1.4?

**Comment by jmprusi** [comment]
@andrewdavidmackenzie yes, this is a type of route in openshift, I can't see why they are going to remove it in the future.

Once we have proper support in apicast, we can change the route type to passthrough and let apicast handle the sni.

**Comment by andrewdavidmackenzie** [comment]
I heard something mentioned about dropping support for self-signed certificates, or something similar...
