### ISSUE TITLE
Swagger compatibility Issue

### ISSUE THREAD

**Issue by sarveshdeveloper** [3scale/APIcast#1393]
Unable to update the swagger version from version 2.0 to 3.0 in 3Scale API Manager, currently 3Scale API Manager is only supporting swagger version 1.2 or 2.0, but both versions have rendering issues, which is been fixed in swagger version 3.0

<img width="1512" alt="Screenshot 2023-02-22 at 5 00 40 PM" src="https://user-images.githubusercontent.com/84385195/220608509-9934a5af-b50b-45e9-b834-69f18c9afe82.png">

is there any work around or fix available for it?

**Comment by es02** [comment]
@sarveshdeveloper Which version of 3scale are you using?

**Comment by sarveshdeveloper** [comment]
hi @es02 we are using 3scale version 2.7.0.

**Comment by eguzki** [comment]
This is not APIcast issue. 

Running 3scale 2.13 I can see OpenAPI  (3.0)

![Screenshot 2023-02-28 at 17-25-09 Service api docs - New Red Hat 3scale API Management](https://user-images.githubusercontent.com/881529/221915506-7108705c-066f-4f9f-b92a-46f3569d9c8d.png)

**Comment by es02** [comment]
@sarveshdeveloper limited support for OAS 3 was introduced in 3scale 2.8.

3scale 2.7 is around 3 years old, you should consider upgrading to a more recent version as functionality is not backported

**Comment by sarveshdeveloper** [comment]
sure, thanks.
