### ISSUE TITLE
Need help with build failure on power

### ISSUE THREAD

**Issue by Chandranana** [3scale/APIcast#1437]
I am trying to add support for apicast on power. Trying build inside container with docker ssupport. We were able to resolve the dependencies needed, and 'make dependencies' successful. However while running make development, it fails for docker compose command inside makefile.

##### Version
master branch

openresty -V
nginx version: openresty/1.21.4.3
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-20) (GCC)
built with OpenSSL 1.1.1k  FIPS 25 Mar 2021
TLS SNI support enabled

##### Steps To Reproduce

1. make dependencies
2. make development

##### Current Result
make development fails with below error when executed inside container:
```
make: [Makefile:208: development] Error 125 (ignored)
/usr/bin/docker compose -f docker-compose-devel.yml -f docker-compose-devel-volmount-default.yml exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" --user : development bash
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

##### Expected Result
make development should succeed.
 
Please let us know if anything is missing to fix this issue.

**Comment by eguzki** [comment]
docker version?

**Comment by tkan145** [comment]
Considered as fixed. Feel free to reopen if you need more help
