### ISSUE TITLE
Change license to Apache2.0

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/apicast#149]
Based in legal input, Apache2.0 is slightly better than MIT, and while all the contributions to the repo are 3scalers (and hence copyright is owned) we can easily switch the license.

So, I propose we do it now - before we accept any 3rd party contributions that complicate the switch.

**Comment by unleashed** [comment]
No one knows this guy, though: `Author: builder <build@localhost>`, 6 commits. Would be good to `filter-branch` her to her real name or (worse) use `.mailmap`.

**Comment by mpguerra** [comment]
maybe a bit off topic, but is this just for apicast or will it also be for all other 3scale repos?

**Comment by andrewdavidmackenzie** [comment]
We will probably go with apache2.0 when possible..... If already open with
MIT and have external contributions already the change is more involved.

**Comment by unleashed** [comment]
Commit list for `builder`:
```shell
commit 54796ff8a9440ddebd5f8509ad166aaf07b3a36f
Author: builder <build@localhost>
Date:	Thu Sep 8 14:38:04 2016 +0200

    Initial template for v2 gateway
    Template for creating the required secret

commit 43cc35b275ea32c53c051b3e185b35b2da4092cb
Author: builder <build@localhost>
Date:	Thu Sep 8 00:43:00 2016 +0200

    check if file is blank or set to avoid trying to load the file always

commit ff1ebac5defd54ac161c380a2e0a44421ac0f97c
Author: builder <build@localhost>
Date:	Thu Sep 8 00:37:56 2016 +0200

    Nginx.conf is not including the contents of the http.d because of bad path

commit d28abf20d9780762dce854935b65149e8440ccdc
Author: builder <build@localhost>
Date:	Wed Sep 7 18:50:18 2016 +0200

    entrypoint was failing on nslookup failure, this fixes the issue by shelling out the var

commit 9414bb05a5f18a0de8771d0fa98bf41eba14477d
Author: builder <build@localhost>
Date:	Wed Sep 7 17:27:32 2016 +0200

    Point to the correct build-image and use pull-policy always

commit 9afb8d4613759b5cdbc6c09df4c131322b2b6958
Author: builder <build@localhost>
Date:	Wed Sep 7 01:34:36 2016 +0200

    adds lua_ssl_trusted_certificate and lua_ssl_verify_depth

    This makes lua find the correct root certificates for SSL certs.

    https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate
```
I think these are made by @jmprusi

**Comment by jmprusi** [comment]
@unleashed that was me, something override my .git global.

**Comment by andrewdavidmackenzie** [comment]
OK, so we have verified that all contributions made to this repo (at the time of writing) were made by 3scale employees (at the time of committing changes) and hence the copyright ownership belongs to 3scale and we can make the license change without further ado. Thanks.
