### ISSUE TITLE
Download of dkjson-2.8.tar.gz failing while executing make dependencies command.

### ISSUE THREAD

**Issue by Shubhamgupta1010** [3scale/APIcast#1494]
Development images is created using the command make dev-build IMAGE_NAME=apicasteimg,
after doing so make development command is working fine, a runtime container is getting created, and inside the container while executing _make dependencies_ command, after installing some dependencies it throws the following error:

`/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/install.lua:59: Error fetching file: Failed downloading http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz - dkjson-2.8.tar.gz
stack traceback:
        [C]: in function 'assert'
        /usr/share/lua/5.1/rover/install.lua:59: in function 'install'
        /usr/share/lua/5.1/rover/install.lua:102: in function 'call'
        /usr/share/lua/5.1/rover/cli/install.lua:42: in function </usr/share/lua/5.1/rover/cli/install.lua:19>
        /usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
        /usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
        [C]: at 0x012fd37c20
make: *** [Makefile:226: lua_modules] Error 1`

##### Steps To Reproduce

1. Create a development image using the make dev build command.
2. import the image in "docker-compose-devel.yml" file
3. run make development and run make dependencies inside the container during runtime

##### Current Result
`/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/install.lua:59: Error fetching file: Failed downloading http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz - dkjson-2.8.tar.gz
stack traceback:
        [C]: in function 'assert'
        /usr/share/lua/5.1/rover/install.lua:59: in function 'install'
        /usr/share/lua/5.1/rover/install.lua:102: in function 'call'
        /usr/share/lua/5.1/rover/cli/install.lua:42: in function </usr/share/lua/5.1/rover/cli/install.lua:19>
        /usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
        /usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
        [C]: at 0x012fd37c20
`

**Comment by eguzki** [comment]
Just now I have build a dev image from the `HEAD` of `main` successfully. 

Maybe due to temporary server issue?

The resource is available. 
```
$ curl -sSf --output /dev/null --silent http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz && echo "success" || echo "fail"
success
```

**Comment by Shubhamgupta1010** [comment]
Thank you worked for me as well.

**Comment by tkan145** [comment]
Happy to hear you sorted it out! 

Consider resolved
