### ISSUE TITLE
[Meta] Enable squash merging on repo

### ISSUE THREAD

**Issue by mpguerra** [3scale/apicast#151]
Can the repo administrator enable squash merging on repo as per [this article](https://github.com/blog/2141-squash-your-commits)? Not sure I like how #150 is currently looking :)

**Comment by davidor** [comment]
You do not need that to improve your PR. You can do it using git. You'll need to become familiar with terms such as `ammend`, `fixup`, and `squash`. `git rebase -i` can help you a lot. A tutorial like this one might help you get started: https://www.atlassian.com/git/tutorials/rewriting-history

**Comment by mpguerra** [comment]
I know, but I tend to mess it up which is why I thought it would be nice and easier if we could just enable that option on the repo ;)

**Comment by mayorova** [comment]
As I understood, this feature does squashing only at the moment of doing a merge. But I think it indeed would be useful to rebase the branch before that, before making the branch ready for review, to make it easier for the reviewer.

**Comment by andrewdavidmackenzie** [comment]
rebasing to make sure the delta is the real delta versus head of master - absolutely.

But different thing from squashing to combine commits and make cleaner, no?

**Comment by jmprusi** [comment]
Sorry, we are not going to enable the squash merging, please rebase your branch correctly before merge (with one or more commits as needed)
