### ISSUE TITLE
access_token is not taken from the Authorization header in OAuth flow

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#161]
Currently the `access_token` for the calls using OAuth flow is taken:
1. from the query parameters (for GET) or body (for POST and other methods), in case the service is configured in 3scale to use headers for credentials locations configured.

2. from `access_token` header

While **1** is OK, **2** is not compliant with the [RFC 6750](https://tools.ietf.org/html/rfc6750), according to which the `access_token` should be taken from the `Authorization` header:

```
Authorization: Bearer xxyyzz
```

This should be fixed.

Another question is whether APIcast should actually check for both locations (thus disregarding the setting in the 3scale configuration) so that it can supports any OAuth client.

**Comment by mikz** [comment]
Imo we should fix this together with the Basic/Digest auth support. Because they are all `Authorization` header.

**Comment by mikz** [comment]
This was not fixed by https://github.com/3scale/apicast/pull/160/commits/4d6c5d14647742f95382f389f74f3fce372ccde7 ?

**Comment by mayorova** [comment]
@mikz No, that was for supporting sending `client_id` and `client_secret` credentials in `Authorization` header for getting the token.
This PR is for passing access token for actual API calls.

**Comment by mikz** [comment]
The section [Authenticated Request](https://tools.ietf.org/html/rfc6750#section-2) describes that the Resource Server MUST to support the Authorization Request Header Field method and that the others are optional.

**Comment by mikz** [comment]
It is possible this was addressed in https://github.com/3scale/apicast/pull/202
because it now always falls back to checking  the access token in the Authorization header as per the RFC (https://github.com/3scale/apicast/issues/161#issuecomment-271298939)
