### ISSUE TITLE
Info for supported config

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/APIcast#168]
There are a number of questions that are asked frequently about apicast, we can help answer them proactively with a FAQ in the repo. I would put in docs folder and also link to it from the readme.

Deployment options
- Customer direct deploy: The customer must deploy supported version of NGINX/OpenResty, and then clone a GA tagged release of the repo. [doc]
- Docker: Customer runs Docker Image from the the official Red Hat Docker Registry, using a supported version of Docker [doc]
- OpenShift: Customer deploys on a supported version of OpenShift a released and unmodified OpenShift template for APIcast, which will run the official Docker images mentioned above

What OS is this project tested on (not implying support)

What version of OpenResty is recommended and tested against?

Failover. If the 3scale Service Management API is unreachable, does the API Gateway continue to work, how?

**Comment by davidor** [comment]
@3scale/documentation Do you think there's something missing in our docs regarding this topic? Otherwise, I'll close this issue.

**Comment by porueesq** [comment]
I think you can close this. We've got some troubleshooting docs. Examples:

-  on OCP: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.5/html/installing_3scale/onpremises-installation#troubleshooting
-    with Docker: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.5/html/administering_the_api_gateway/apicast-docker-advanced#troubleshooting_apicast_on_the_docker_containerized_environment

**Comment by davidor** [comment]
Thanks @porueesq !
