### ISSUE TITLE
Add TROUBLESHOOTING

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/APIcast#169]
While getting apicast running and integrated with 3scale API Management Platform a number of issues can arise that are not familiar or easy to debug for new users. We wish to make this start-up and integration process as easy and painless as possible for new users.

To do so, we would like to add to this upstream project a document where possible sources of problems are documented as a resource for people to use to help them get going.

I suggest adding in doc folder and linking from the README.

This would be an upstream document, focused on apicast alone, based on learnings of 3scale over the years captured in this product document. 
https://support.3scale.net/docs/api-devops/troubleshooting

When resolving issues, or finding new causes, anyone can PR this document to add cases that may help other users int he community solve their problems.

**Comment by vramosp** [comment]
It'd be good to add a section about troubleshooting on OpenShift, which is a relatively new scenario. We're already getting questions about it.

**Comment by davidor** [comment]
@3scale/documentation This is an old issue and we have added a lot of documentation since then. Do you think there's something missing regarding troubleshooting? Otherwise, I'll close this issue.

**Comment by porueesq** [comment]
I think you can close this. We've got some troubleshooting docs. Examples:
* on OCP: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.5/html/installing_3scale/onpremises-installation#troubleshooting
* with Docker: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.5/html/administering_the_api_gateway/apicast-docker-advanced#troubleshooting_apicast_on_the_docker_containerized_environment

**Comment by davidor** [comment]
Thanks @porueesq
