### ISSUE TITLE
Add APIcast 2.0 OpenShift template to ansible-openshift installer

### ISSUE THREAD

**Issue by vramosp** [3scale/apicast#175]
Add the APIcast 2.0 OpenShift template to the Ansible-Openshift installer, so when the customer installs OpenShift, the APIcast templates gets automatically installed.

The GitHub repository is this:
https://github.com/openshift/openshift-ansible

**Process**
From @sdodson: We just sync the file from your upstream repo into the installer repo. Your teams can either open pull requests against openshift-ansible or email me and let me know the new tag to
include and we'll update it then.

**Comment by vramosp** [comment]
The productized template can be found here https://github.com/3scale/rhamp-openshift-templates
Nothing else required from engineering.

**Comment by andrewdavidmackenzie** [comment]
This will be overwritten in the future with the AMP 2.0 release apicast
template, correct?

New issue for that task?

**Comment by vramosp** [comment]
I don't think it's needed. Nothing additional required from engineering.

**Comment by andrewdavidmackenzie** [comment]
I just mean that we'll need to remember to do the same action with the final template when we do GA of AMP 2.0 ..... will leave to you on how to ensure that is done.
