### ISSUE TITLE
Document APIcast parameters

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#178]
There is a number of parameters that can be set for APIcast that modify its behavior, normally they are set via environment variables (e.g. `AUTO_UPDATE_INTERVAL `, `APICAST_SERVICES`, `APICAST_MISSING_CONFIGURATION` etc.)

All these parameters need to be documented: the name, what they do, what are the allowed values/format.

I think this needs to be a separate reference document.

**Comment by mikz** [comment]
We try to document them in https://github.com/3scale/apicast/blob/v2/.env

**Comment by andrewdavidmackenzie** [comment]
Agree good to document somewhat in one 'doc' that is not code, but having in too many places causes an update overhead.

Thinking about your (valid) example of someone installing from OpenShift template and not seeing the code.... made me wonder what documents or mechanisms for showing information are available....  I think Joaquim mentioned to me the ability to embedd some "notices" in the template itself and they are shown to the user .... for that use case that might be a better place?

**Comment by mikz** [comment]
Someone installing from OpenShift template will see all of them as template parameters in the UI. Each param has description.

**Comment by mayorova** [comment]
Closed by https://github.com/3scale/apicast/pull/192
