### ISSUE TITLE
Track gateway usage

### ISSUE THREAD

**Issue by vramosp** [3scale/apicast#182]
It seems that with latest releases we've lost the ability of using the user agent header to track source of calls to backend and we'd like to bring it back.

In addition, it'd be useful to also being able to track:
- Deployment method
- Modules used

**Comment by MarkCheshire** [comment]
We should really aim to get this included in the initial release.

**Comment by mikz** [comment]
The initial release was already shipped on 2016-11-28.

**Comment by mikz** [comment]
I started the implementation of the full User-Agent which will look like following: `APIcast/2.0 (OSX; x64; env:production) APIcast/2.0`

It follows the [RFC 7231 section 5.5.3](https://tools.ietf.org/html/rfc7231#section-5.5.3) and [best practices by Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#Syntax).

It includes information about:

* APIcast core version
* APIcast module version (or any other loaded module, like XC)
* platform
* architecture
* deployment environment

And will be sent in the `User-Agent` header. 

For comptatibility purposes there will also be the `X-3scale-User-Agent` set to `APIcast/2.0+env` tracking the APIcast module version, not the core so XC and other modules can set their own.

**Comment by andrewdavidmackenzie** [comment]
Would be good to check with URI, that it's easily parseable in Grafite, as
that's what we used to get some stats on usage by plugin/gateway....

**Comment by mikz** [comment]
@3scale/operations could you verify `User-Agent` string like that would be ok for us to track use? If not, can you suggest some changes?

**Comment by jmprusi** [comment]
yes, should be easy to track

**Comment by MarkCheshire** [comment]
@pili can you please comment based on experience of the current trackers

**Comment by mpguerra** [comment]
The only thing I'm wondering now is whether it makes sense to use the User-Agent header in the same way for the other APIcast versions/plugins and use the X-3scale-User-Agent header for additional info also

**Comment by mikz** [comment]
Is it still useful to have a timestamp of the configuration in the headers? 
It got broken https://github.com/3scale/apicast/issues/216#issuecomment-271996521 and I'm not sure if it is useful enough to fix it.
