### ISSUE TITLE
[OAuth] Make access token ttl configurable

### ISSUE THREAD

**Issue by mpguerra** [3scale/apicast#190]
Currently, the access token ttl is hardcode at 7 days (604800 seconds.)

Ideally we should be able to override this without changing the lua code.

**Comment by michaelcurry** [comment]
After some discovery and talking through the issue with 3Scale support, we have found the issue to be here: https://github.com/3scale/apicast/blob/1aa004d5a84c0bbd521c3c36dad5001a254ded54/apicast/src/oauth/apicast_oauth/get_token.lua#L43

This is Forcing the TTL to be 7 days (604800 Seconds).  Because we need to make non-Expiring tokens, we need this to be a variable.

Please let us know the ETA on this change.

**Comment by rnavarro** [comment]
+1 We're currently overriding our lua code to make this work for us.

I would rather this be pushed up stream so we don't diverge.

**Comment by michaelcurry** [comment]
Looking deeper into this issue, it looks like the only way to create a non-expiring token is to NOT send the `TTL` variable at all.  this means we want to be able to set it dynamically, but if we pass `0` the code should not send the TTL in the payload at all.

**Comment by mikz** [comment]
That should be easy enough by setting the value to nil. I guess we could introduce an environment variable to set this ? Something like `APICAST_OAUTH_ACCESS_TOKEN_TTL` ?

**Comment by mpguerra** [comment]
Yes, @michaelcurry a bit of an update further to our conversation yesterday, currently you create a non-expiring token by NOT sending `TTL` parameter as you correctly state. 

However, very shortly (next few weeks) we will be implementing a change to this so that sending a `TTL` is mandatory and you need to send a value of 0 for non expiring tokens. 

We will be sending a note to all affected accounts in the next few days. 

@mikz yes, sounds good

**Comment by mpguerra** [comment]
@kevprice83 FYI

**Comment by rnavarro** [comment]
Any update on making this parameter a variable?

**Comment by mikz** [comment]
@rnavarro would you be ok with ENV variable setting the TTL ?

**Comment by rnavarro** [comment]
Yes that works.
