### ISSUE TITLE
Unify parameter names

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#207]
Some parameters start with `THREESCALE_` and some with `APICAST_` and some with no prefix at all. Some don't match their name in the OpenShift template.

##### Expected Result

All parameters in the OpenShift template should follow the same format. They don't have to necessarily be the same as the APIcast environment variable, because the prefix might be redundant.

Reported in https://github.com/3scale/apicast/pull/176

**Comment by thomasmaas** [comment]
@mikz this would also be a valid issue for amp template right?

**Comment by mikz** [comment]
Yes. 

24. 1. 2017 v 18:10, Thomas Maas <notifications@github.com>:

**Comment by andrewdavidmackenzie** [comment]
Probably need a heads-up for any documentation changes that will be needed outside the repo due to this?

**Comment by mikz** [comment]
Yes. That's another reason why it wasn't done yet. There is not clear proposal and it would require coordination. 

Odesláno z iPhonu

24. 1. 2017 v 18:34, Andrew Mackenzie <notifications@github.com>:

**Comment by vramosp** [comment]
@mikz This is done, can it be closed?

**Comment by mikz** [comment]
The upstream template is not fixed yet.
