### ISSUE TITLE
Release 3.0.0 Alpha 1

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#211]
Release 3.0.0 Alpha 1 with changes from 2.0.0.

Also tag it as `RHAMP-2.0-ER2`.

**Comment by andrewdavidmackenzie** [comment]
Tag RHAMP-2.0-ER2 also?
Double tag?

**Comment by mikz** [comment]
Done https://github.com/3scale/apicast/releases/tag/v3.0.0-alpha1 https://github.com/3scale/apicast/pull/223
