### ISSUE TITLE
service:extract_usage() does not work when credentials are sent in the headers

### ISSUE THREAD

**Issue by davidor** [3scale/apicast#215]
The reason is that the `get_auth_params` method in `configuration.lua` checks uri params and POST bodies, but not the headers: https://github.com/3scale/apicast/blob/6065ac35fe23fb53a240a91832db7b2938d8ebac/apicast/src/configuration.lua#L77

**Comment by mikz** [comment]
But `extract_usage` should not extract usage from headers. Only from GET/POST params.

**Comment by davidor** [comment]
Sorry @mikz I was confused. This is not an issue.
The `get_auth_params` method name confused me. The name made me think that the method returned auth credentials (app_id, app_key), but that is not what it does or should do.

**Comment by mayorova** [comment]
@davidor actually has a good point.
This method probably should be called just `get_params` to avoid confusion.

**Comment by mikz** [comment]
That whole getting usage is begging for refactoring which will come :)
