### ISSUE TITLE
Debug header does not work

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#216]
When the `X-3scale-debug` header with the provider key as its value is sent to the APIcast, it should add the debug headers with the response.

This was broken after [splitting the configuration](https://github.com/3scale/apicast/pull/198), as [`_M.configuration.debug_header`](https://github.com/3scale/apicast/blob/138d23c79c5fd66afae9c3e4a12da7f6fb5d655e/apicast/src/provider.lua#L116) does not exist, as it's referring to `configuration_store.lua` and not `configuration.lua` as before.

**Comment by mayorova** [comment]
Another affected field is: https://github.com/3scale/apicast/blob/master/apicast/src/provider.lua#L298

**Comment by mikz** [comment]
I'm thinking about how to get rid of the provider key in the debug header.
Also the version should be scoped by service. Basically there should be no global configuration and everything should be scoped by service.

One of the options is to have different debug header for each  service I'm considering the service token. It is already there and users already have access to it. So it kind of feels like natural way to have per service secret for the debug header. Wdyt?

**Comment by mayorova** [comment]
The problem is that if you have multiple services configured, it would be a bit hard to know what service the request will be mapped to (especially when using path-based routing). I know that we are planning to remove the provider key from the JSON spec, but I don't know what would be a reasonable alternative :/

**Comment by mikz** [comment]
@mayorova I'd consider it almost a feature. If you get the header back when using path based routing, you know it routed right :) 
But yeah, I see the issue. Not sure what we can do about it right now. IMO each service should have unique token because they are independent and one person does not have to have access to all of them.
