### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#23]
Would be nice to get some feedback on how we should improve logging.

From debugging and troubleshooting to logging request times.

**Comment by mpguerra** [comment]
One thing that people always want to know is the time it takes for the response from the API to be sent to the client. 

Another one is time spent in roundtrip to 3scale

**Comment by andrewdavidmackenzie** [comment]
@tnscorcoran @mayorova @davidor @mpguerra and any others - if you can provide feedback on desired logging (or even better submit a PR to do it) to help you debug issues - then we will consider implementing.

Otherwise in a couple of weeks I'll close this issue.

**Comment by mpguerra** [comment]
Another thing that is useful is the actual call that the gateway makes to 3scale for authorization. This is normally the sort of data that we tend to go to kibana for since we can't find it in the logs.

**Comment by mikz** [comment]
I'd say it also logs the real call to 3scale now:

```
2017/01/12 10:03:39 [info] 29976#0: *11 [lua] provider.lua:172: get(): [http] http://127.0.0.1:1984/transactions/authrep.xml?service_token=service-two&service_id=21&usage[hits]=2&app_key=two-key&app_id=two-id (200) while sending to client, client: 127.0.0.1, server: localhost, request: "GET /two?app_id=two-id&app_key=two-key&host=two HTTP/1.0", host: "127.0.0.1"
```

Feel free to reopen and make a list with new ideas.
