### ISSUE TITLE
The link to the Openshift Template for releas v2 is incorrect

### ISSUE THREAD

**Issue by tonswieb** [3scale/apicast#232]
The documentation in https://github.com/3scale/apicast/tree/v2.0.0, contain an invalid Openshift Template URL.

It referes https://raw.githubusercontent.com/3scale/apicast/v2/openshift/apicast-template.yml but should be https://raw.githubusercontent.com/3scale/apicast/v2.0.0/openshift/apicast-template.yml

**Comment by tonswieb** [comment]
The tutorial from http://pages.3scale.net/openshift-gateway-redhat.html also contains outdated links.

**Comment by mikz** [comment]
Thanks for noticing!

Pushed `v2` tag pointing to `v2.0.0` that fixed all references to the deleted branch.

Feel free to reopen if there are more invalid links.
