### ISSUE TITLE
[OAuth] Provide an endpoint to revoke access tokens

### ISSUE THREAD

**Issue by mpguerra** [3scale/apicast#243]
We're currently lacking a built in way to revoke access tokens. 

This would probably just be an endpoint that can be called to delete a token from the 3scale backend.

**Comment by mpguerra** [comment]
@kevprice83

**Comment by mikz** [comment]
The traditional OAuth part is (going to be) deprecated, can we close this issue?

**Comment by davidor** [comment]
I think so @mikz
