### ISSUE TITLE
APIcast does not print "no config loaded" in error logs

### ISSUE THREAD

**Issue by kevprice83** [3scale/apicast#246]
When launching the gateway locally - native deployment (OSX) the error log does not print any warnings or errors.

[output](https://gist.github.com/kevprice83/e2be8c8130afa1c9d79a77276d210d73)

A request to the gateway or management API results in a 500 response.

To the management API the following is printed to the error logs

[error log](https://gist.github.com/kevprice83/81405c83ae1566c3971bbc6db996654b)

It seems that the version of Openresty I was using was the cause `nginx version: openresty/1.11.2.1 (no pool)`

Updating this to latest version fixed the issue. It would be useful to have this error related to no configuration being loaded printed to the logs however.

cc @mikz

**Comment by mikz** [comment]
I'm trying to simulate this by requiring a file that does not exist in `libexec/boot` but without any luck.
It always prints the stderr. If you have steps to reproduce I'll be happy to take another look.
