### ISSUE TITLE
find_service fails in post_action when path based routing is enabled

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#254]
When `APICAST_PATH_ROUTING_ENABLED=1`, `find_service` function works as expected in the rewrite phase, but in post_action, when the service is searched again, the find function has some issues:

- `self` argument is missing [here](https://github.com/3scale/apicast/blob/a676ae5c0067aab43078bd9ddc32f6c7a14eb26c/apicast/src/proxy.lua#L169)
- ~~`find_service_cascade` can't find the correct service, as service_id is passed to it (instead of the host), so it falls back to `find_service_strict`, and may not find the correct service, which will result in an incorrect authrep~~ 
 UPDATE: `find_service_strict` WILL find the correct service, because it will search by service_id, not the host

**Comment by kevprice83** [comment]
Although I have this working locally with my `custom_config` for url rewriting my customer are running this on the latest Docker image in the 3scale registry and it's breaking when running multiple services. I can provide them a fix which will be attached as a volume in the meantime but it would be great to get this merged asap :)

**Comment by mikz** [comment]
This is fixed in https://github.com/3scale/apicast/pull/253 by https://github.com/3scale/apicast/pull/258
