### ISSUE TITLE
Add support for end-user plans

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#255]
Currently End User plans are not supported in APIcast (except for the OAuth flow), and it should. `service:extract_credentials()` need to return `user_id` as parameter if it is provided in the request (so that it's also supported by XC).

It would be good to have a separate function to extract the `user_id` param, by default taking the value from query or body params, or headers (similar to app credentials), and have an easy way to customize this function to be able to extract the user ID from another parameter (JWT token, param with a different name etc.).

**Comment by davidor** [comment]
Closing this as the support for end users has been deprecated in 3scale.
