### ISSUE TITLE
Specify minimal required OpenResty version

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#269]
APIcast relies on the [split()](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/re.md#split) function of the [lua-resty-core](https://github.com/openresty/lua-resty-core), which appeared in [v0.1.9](https://github.com/openresty/lua-resty-core/releases/tag/v0.1.9).

As consequence, the minimal supported version of OpenResty is `1.11.2.2`. This should be specified in the docs for local installation, and probably included to the troubleshooting doc.

**Comment by mikz** [comment]
The version we test against is specified in .travis.yml: https://github.com/3scale/apicast/blob/b933f97b197a9e5dcfbfa00cd3713fe1e0ffa769/.travis.yml#L34
And the version we build against is in the Makefile:
https://github.com/3scale/apicast/blob/b933f97b197a9e5dcfbfa00cd3713fe1e0ffa769/Makefile#L12-L14

**Comment by mikz** [comment]
We moved to CircleCI - https://github.com/3scale/apicast/blob/5bc65431b6395d175e07f5d162e43a12a70bb537/.circleci/config.yml#L10

Our CI is the source of truth for which OpenResty version we test against and ship.
We are not going to test older versions to figure out what is the minimal required version.
