### ISSUE TITLE
Add redis to OpenShift template to enable OOB OAuth (in tech preview)

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/apicast#279]
Currently it's extra manual steps to add redis so that OAuth2.0 works.

We have discussed making OAuth available Out-of-the-box in CR/GA - but only in "Tech Preview" i.e. it is not fully mature and needs testing by us and QE.

So, I wanted to force the debate on what to do with the dependency on redis and if we want to include it in the template (here or in AMP - AMP could be a separate issue in that repo) so it's easy to use....we should decide this very soon after ER4 and then close it and not make changes later before ER5.

**Comment by andrewdavidmackenzie** [comment]
Ping @vramosp @MarkCheshire @mikz

**Comment by MarkCheshire** [comment]
One thing I struggle with is how to package this and set the right support expectations. For OpenResty we say if it is in the templates/images we support it. However we don't want to extend that same support statement to Redis (unless it is covered by Software Collections) because we don't want to get sucked into all the configuration questions of Redis in HA which is not trivial.

This is pending @vramosp investigation to SCL. But if Redis is not covered, would there be a way to differentiate it in the template. Otherwise we may need to call out exceptions in docs.

**Comment by mpguerra** [comment]
What we actually use Redis for is pretty trivial, I would vote for removing as many dependencies as possible. 

We could probably rewrite the code to not use it and just do the same thing in the lua cache.

**Comment by mikz** [comment]
To support multiple nodes we would have to use cryptography like JWT to share the state between different nodes. There is issue already https://github.com/3scale/apicast/issues/174

Using something like:
https://github.com/bungle/lua-resty-session
or https://github.com/openresty/encrypted-session-nginx-module

**Comment by MarkCheshire** [comment]
@mpguerra we do not want to introduce any blockers to publishing the tutorial. This can be handled as an enhancement to remove the Redis dependency but we are already 2 months late with the tutorial. Following that is high priority to have all OAuth flows supported OOTB with APIcast. If removing Redis accelerates that they it could be covered, but if it impacts the timing significants, then better to keep the Redis dependency. We also have to consider the longer term architecture for OAuth and it may be good have that discussion before removing the Redis dependency.

**Comment by vramosp** [comment]
@MarkCheshire Not sure what investigation you mean... but my understanding is that the version of Redis that we're using is included in SCL.

**Comment by vramosp** [comment]
After discussions with different people involved, agreed that for the next release we will solve this need in built-in apicasts only, see https://github.com/3scale/openshift-templates/issues/161

In the future we'll try to remove the Redis dependency, so closing this in favor of that.
