### ISSUE TITLE
OAuth2.0 ACF not working OOTB

### ISSUE THREAD

**Issue by lucamaf** [3scale/apicast#282]
the Oauth flow is not working as expected out the box

##### Version
using Docker image with Redis.
Gateway version: 2017-02-24T12:52:53.048599228Z

##### Steps To Reproduce
1. configured Keycloak as Authorization server by copying the details of the application
<img width="443" alt="oauth1" src="https://cloud.githubusercontent.com/assets/1726883/23610352/68bdbe7c-0272-11e7-94d2-b0a2d01976c0.PNG">
<img width="661" alt="oauth2" src="https://cloud.githubusercontent.com/assets/1726883/23610392/96791e88-0272-11e7-9234-ef830e0175f3.PNG">
2. configured the OAuth endpoint in the API integration part and the relative Public Base URL of the docker image
<img width="617" alt="oauth3" src="https://cloud.githubusercontent.com/assets/1726883/23610454/d805d1a2-0272-11e7-9196-7c3d37cba5fd.PNG">
<img width="682" alt="oauth4" src="https://cloud.githubusercontent.com/assets/1726883/23610456/d808a292-0272-11e7-89b5-79726edb867e.PNG">
3. using Google OAuth Playground to execute the test
https://developers.google.com/oauthplayground/#step1&url=https%3A//&content_type=application/json&scopes=openid&http_method=GET&useDefaultOauthCred=unchecked&oauthEndpointSelect=Custom&oauthTokenEndpointValue=http%3A//ec2-52-59-215-163.eu-central-1.compute.amazonaws.com:8081/oauth/token&oauthClientId=865dc16a&oauthClientSecret=ae83b0d0000bad63e3ddbe6c52a42298&includeCredentials=checked&accessTokenType=query&autoRefreshToken=unchecked&accessType=offline&forceAprovalPrompt=checked&response_type=code&oauthAuthEndpointValue=http%3A//ec2-52-59-215-163.eu-central-1.compute.amazonaws.com:8081/authorize
4. this results in a 500 error on the gateway
<img width="695" alt="oauth5" src="https://cloud.githubusercontent.com/assets/1726883/23610881/c40fa4dc-0274-11e7-99ec-66611fbe749e.PNG">

##### Current Result
500 error
##### Expected Result
redirect to keyloak consent page
##### Additional Information
 NGINX log 
[logs.txt](https://github.com/3scale/apicast/files/821189/logs.txt)

**Comment by mikz** [comment]
Is redis configured? I guess @mpguerra could help you as she was doing the OAuth demo.

**Comment by andrewdavidmackenzie** [comment]
Yes, if by "Out of the box" you mean "without doing any config" then that's the way it is (to date) and as expected....you need to configure apicast to use a redis .... as per demo by Pili

**Comment by mpguerra** [comment]
Integration with RHSSO was never going to work OOTB.

APIcast requires an Authorization Server to call it back directly, strictly for the purpose of letting APIcast know a user has authenticated and provided consent.

Keycloak is expecting direct communication with a client, it is not expecting mediation via APIcast. 

If you look at the examples of Authorization server used, in every case the consent page calls back APIcast, instead of the client directly, to let APIcast know the end user is authenticated and has consented access to their data. 

Furthermore, Keycloak only supports OIDC, whereas APIcast only supports "plain" Authorization Code flow.

Integration with Keycloak is coming soon though.

**Comment by mikz** [comment]
So if there is plan for some Keycloak integration lets create an issue for it with proper description and requirements ? Then we could just close this referring to that issue.

**Comment by vramosp** [comment]
@lucamaf What version are you using?

**Comment by kevprice83** [comment]
I'm also getting a 500:

I am only using the Auth server provided by the workshop in 3scale.

Auth server is running on `[heroku](https://authserverapi.herokuapp.com/)`

The client is running locally and set up as per the instructions [here](https://github.com/3scale/apicast/tree/master/examples/oauth2)

Redis is running on OpenShift as well as the gateway.

Request:
```GET /authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope= HTTP/1.1
Host: threescalegw-3scalegateway-heroku.52.91.49.129.xip.io
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: http://localhost:9292/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ca;q=0.6,es;q=0.4,pt;q=0.2
Cookie: 04093eb0eaee2297f074228f1b552e42=c170442a3cb26bc29fa810f59f41d149``` 

This directs me to the login on the UserGoals API which then asks for authorization to access. I am expecting to then be redirected to the client as stated in the `callback` parameter.

But I get a 500 with error message `NOAUTH Authentication required.`

Logs from the gateway are as below:

```2017/03/13 16:48:10 [info] 22#22: *1508 [lua] balancer.lua:110: set_peer(): balancer set peer 174.129.235.69:443 while connecting to upstream, client: 172.17.0.1, server: _, request: "GET /authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope= HTTP/1.1", subrequest: "/_threescale/check_credentials", host: "echo-api.3scale.net", referrer: "http://localhost:9292/"
2017/03/13 16:48:10 [info] 22#22: *1508 [lua] proxy.lua:403: post_action(): [async] skipping after action, no cached key while sending to client, client: 172.17.0.1, server: _, request: "GET /authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope= HTTP/1.1", host: "echo-api.3scale.net", referrer: "http://localhost:9292/"
2017/03/13 16:48:10 [info] 22#22: *1508 [lua] log_by_lua(apicast.conf:48):3: [authrep] /authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope= 500 while logging request, client: 172.17.0.1, server: _, request: "GET /authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope= HTTP/1.1", host: "echo-api.3scale.net", referrer: "http://localhost:9292/"
[13/Mar/2017:16:48:10 +0000] threescalegw-3scalegateway-heroku.52.91.49.129.xip.io:8080 172.17.0.1:42064 "GET /authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope= HTTP/1.1" 500 43 (0.036) 0
2017/03/13 16:48:10 [info] 22#22: *1508 [lua] proxy.lua:40: access(): no credentials provided for service 2555417740411, client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "echo-api.3scale.net", referrer: "http://threescalegw-3scalegateway-heroku.52.91.49.129.xip.io/authorize?state=c15ac9e6-2eed-4771-8b7d-0cc3733af616&response_type=code&client_id=66cd94cc&redirect_uri=http%3A%2F%2Flocalhost%3A9292%2Fcallback&scope="```

**Comment by kevprice83** [comment]
ADDITIONAL: I am not trying to integrate with an iDP of course, just the OOTB flow and using access_tokens

**Comment by kevprice83** [comment]
UPDATE: It looks like there is some bug with either the example auth server and client

The callback request returns the following:

`http://17475b9c.ngrok.io/callback?code=c0c300894a9a53c03496957d629b5830e4be648f&state=40a0c491-4f41-4b4a-adbc-119c9acc6047`

As you can see the code has been generated but the client is giving the message `error: state does not match`

Aside from this the most important things to note and include in a troubleshooting as well as update our own documentation are the following points:

- the auth server or IdP must redirect to http otherwise https has to be configured in OpenShift
- Redis template taken from the origin upstream project includes a password to connect to Redis
  - Either this must be removed from the template to allow the gateway to execute methods inside Redis or the gateway logic must be updated to extract the value of the password from the ENV variable in OpenShift

cc @mpguerra

**Comment by kevprice83** [comment]
This was fixed for my testing as per the reference from Daria. The issue was with the state value and example auth server. I am closing this now as the RH SSO integration is already released.
