### ISSUE TITLE
Remove ability for apicast to send request logs to backend

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/apicast#291]
We are planning to remove the request logs functionality from AMP (System and Backend, initially Cubert-based request logs and then Redis-based request logs).

So, I propose that we avoid creating more "legacy" by having apicast have the ability (enabled by an ENV variable) to send request_logs to the Service Management API - by removing this functionality from apicast now, prior to CR1 release.

**Comment by lucamaf** [comment]
is the integration with EFK stack in OSE already working?

**Comment by mikz** [comment]
Thats nice because it is one of the blockers for fully removing post_action as shown in https://github.com/3scale/apicast/pull/290.

**Comment by andrewdavidmackenzie** [comment]
Keeping reporting of response codes though!!

**Comment by mikz** [comment]
That does not make it easier then. Response codes still need the post_action.

**Comment by kevprice83** [comment]
What if the response codes were always reported as a separate call. So first authorize then report? This will actually be slightly more accurate as the first call won't be lost. No need for post_action then

**Comment by mikz** [comment]
1) still need for post_action to know the response code (even though later it can be asynchronous)
2) doubling the calls to backend might not be the smartest idea 
3) not sure if someone tried reporting logs with no usage

**Comment by andrewdavidmackenzie** [comment]
@vramosp @3scale/documentation  Any docs requiring updating to remove this option?
