### ISSUE TITLE
Include template for Redis for OAuth flow (Openshift)

### ISSUE THREAD

**Issue by kevprice83** [3scale/apicast#300]
### Solution

Use the redis template from [Origin upstream](https://github.com/openshift/origin/tree/master/examples/db-templates) 

Unfortunately this won't work "as is" for APIcast deployed on OpenShift. So the following changes need to be made.

- Either an ImageStream needs to be created or directly editing the config for Redis to include the URL of the registry where the image is hosted. Without this change in the default template the deployment config cannot pull the image. 

- Also the default template includes setting a password to access the Redis instance. 
  - Either the gateway logic needs to be updated to grab this value from the `ENV` and execute all Redis actions with the password or remove the password completely from the template as I have done in my [template](https://github.com/kevprice83/origin/blob/kevprice83-redis-no-password/examples/db-templates/redis-ephemeral-template.json)

We should cover in more detail the documentation of the specifically setting this up in OpenShift as the OAuth flow is a bit trickier to set up here than native deployment for example.

**Comment by mikz** [comment]
APIcast is indeed missing password support in redis. 
OpenShift example redis example not working is not APIcast problem at all.

Did you try to set the password to empty by using `--param REDIS_PASSWORD=""` when importing the template? Haven't tried just, so no idea if it works or still generates new password.

**Comment by mayorova** [comment]
I've used this modified apicast template to deploy Redis: https://gist.github.com/mayorova/9825ebea7885335c5540c027023474c8

**Comment by kevprice83** [comment]
It's not an APIcast problem right, but we have a dependency on Redis so I think it makes sense we provide a template to make that work in our deployment option on OpenShift. I just wanted to share how I made that work along with the issue itself. So let me reword the issue itself so it seems more appropriate here.

I did remove the password but the template sets the `REDIS_PASSWORD` as en ENV so all of these parameters need to be removed from the config.

**Comment by mikz** [comment]
When importing the template you can set params otherwise they are generated. If you'd set REDIS_PASSWORD as a param all that should be set to empty password and possibly work.

Anyway, we should add password support. Probably with unifying the configuration into an url: `redis://password@host:port/db`.

**Comment by mikz** [comment]
We are going to support password in Redis connection https://github.com/3scale/apicast/issues/301 + https://github.com/3scale/apicast/pull/303. So this should be changed to pure documentation issue.

**Comment by davidor** [comment]
The OAuth flow is deprecated. Closing.
