### ISSUE TITLE
service token not created automatically

### ISSUE THREAD

**Issue by lucamaf** [3scale/apicast#338]
when I created a new service on MT the Service Token wasn't created automatically, this resulted in denied calls by APICAST

##### Version
2017-03-27T13:20:03.37060525Z

##### Steps To Reproduce
1. [config.json.txt](https://github.com/3scale/apicast/files/874053/config.json.txt)
2. curl -X GET -H "user-key: b8957d180982cde697d8cc14d68aff65" "http://ec2-54-93-107-1.eu-central-1.compute.amazonaws.com:8080/test/hello"

##### Current Result
Authentication failed

##### Expected Result
200 OK

##### Additional Information
I added a custom module to strip the first part of the path, you can find it attached.
[url_strip.lua.txt](https://github.com/3scale/apicast/files/874056/url_strip.lua.txt)

**Comment by lucamaf** [comment]
the related MT link is https://finaviapoc-admin.3scale.net/apiconfig/services/2555417740930/integration/edit

**Comment by kevprice83** [comment]
I guess this actually belongs in system repo as it is system that handles this itself.

**Comment by mikz** [comment]
This has nothing to do with APIcast. It is data synchronisation issue between other services.
