### ISSUE TITLE
Add support for Refresh Token flow in RH SSO integration

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#367]
While RH SSO supports refresh token flow, APIcast currently doesn't let the refresh token requests pass through.

Firstly, `refresh_token` is not among the [allowed grant types](https://github.com/3scale/apicast/blob/v3.0.0/apicast/src/oauth/keycloak.lua#L20-L24), and further handling of such request is not implemented either.

It would be good to have it.

**Comment by mikz** [comment]
The traditional OAuth part is (going to be) deprecated, can we close this issue?

**Comment by mayorova** [comment]
@mikz Yes, this request is not relevant anymore, it was for the old RH SSO integration, when APIcast proxied the access token requests.
