### ISSUE TITLE
APIcast fails CORS preflight request

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#369]
When accessing an API protected by APIcast from a browser on different domain the browser is going to send CORS Preflight request. That is going to miss the authentication and not succeed.

We should investigate what would be the correct path forward (using Access-Control-Allow-Credentials, Access-Control-Allow-Headers, other ideas?) .

Source: https://stackoverflow.com/questions/44261553/cors-with-3scale

**Comment by davidor** [comment]
You already solved this problem, right? 
https://github.com/3scale/apicast/tree/3.1-stable/examples/cors

**Comment by mikz** [comment]
Could be solved, but we should verify.

**Comment by davidor** [comment]
Works for me using the new CORS policy.
