### ISSUE TITLE
Confusing "sandbox" name for Staging environment

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#370]
Currently the available values for the `THREESCALE_DEPLOYMENT_ENV` is `production` or `sandbox`. While production is clear enough, `sandbox` is quite confusing because the environment in 3scale is called "Staging". 

I suggest that `staging` is added as an alias, while keeping `sandbox` too for backward compatibility.

**Comment by hallelujah** [comment]
I guess it should be the other way around: Aliasing `staging` to `sandbox` in 3scale.
Sandbox really means sandbox unlike staging is too generic

**Comment by mayorova** [comment]
Well, either way would work as long as the user can specify `THREESCALE_DEPLOYMENT_ENV=staging` and expectedly get the Staging environment configuration.

**Comment by mikz** [comment]
The 3scale API now aliases `staging` to `sandbox` so you can use `THREESCALE_DEPLOYMENT_ENV=staging`.
