### ISSUE TITLE
APIcast Self-Managed on RHEL7 

### ISSUE THREAD

**Issue by ptyagii** [3scale/apicast#373]
##### Version
openresty -v
nginx version: openresty/1.11.2.3

Operating system details: 
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.3 (Maipo)"
ID="rhel"
VERSION_ID="7.3"

##### Steps To Reproduce

1. Follow the instruction given on page [1]  to deploy and run apicast v2 
2) Start APIcast using the below command: 

THREESCALE_PORTAL_ENDPOINT=https://<ACCESS_TOKEN>@<DOMAIN>-admin.3scale.net bin/apicast -v

Change ACCESS_TOKEN and DOMAIN as per the link [1] 

[1] https://support.3scale.net/docs/deployment-options/apicast-self-managed

##### Current Result

2017/06/12 11:53:16 [emerg] 30283#30283: SSL_CTX_load_verify_locations("/home/apicast/apicast/conf/ca-bundle.crt") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/home/apicast/apicast/conf/ca-bundle.crt','r') error:2006D002:BIO routines:BIO_new_file:system lib error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)
2017/06/12 11:53:17 [notice] 30262#30262: signal 17 (SIGCHLD) received
2017/06/12 11:53:17 [notice] 30262#30262: worker process 30283 exited with code 2
2017/06/12 11:53:17 [alert] 30262#30262: worker process 30283 exited with fatal code 2 and cannot be respawned

##### Additional Information

1) ls -l ca-bundle.crt 
-rw-rw-r-- 1 user user 261889 Jun 12 12:03 ca-bundle.crt

2) ran a) and b) commands with root access: 

a) luarocks make apicast/*.rockspec --tree /usr/local/openresty/luajit
b) [root@user apicast]# THREESCALE_PORTAL_ENDPOINT=https://<ACCESS_TOKEN>@<DOMAIN>-admin.3scale.net bin/apicast -v

3) Running below command gives the same error: 

THREESCALE_PORTAL_ENDPOINT=libexec/boot bin/apicast -v

2017/06/12 18:09:40 [emerg] 16932#16932: SSL_CTX_load_verify_locations("/home/apicast/apicast/conf/ca-bundle.crt") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/home/apicast/apicast/conf/ca-bundle.crt','r') error:2006D002:BIO routines:BIO_new_file:system lib error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)
2017/06/12 18:09:41 [notice] 16911#16911: signal 17 (SIGCHLD) received
2017/06/12 18:09:41 [notice] 16911#16911: worker process 16932 exited with code 2
2017/06/12 18:09:41 [alert] 16911#16911: worker process 16932 exited with fatal code 2 and cannot be respawned

**Comment by kevprice83** [comment]
@ptyagii did you make any progress with this?

**Comment by ptyagii** [comment]
@kevprice83 no, still getting the same error.

**Comment by mayorova** [comment]
I just tried on a fresh RHEL 7.3 instance, and it works fine for me when starting APIcast as a normal user, not as **root**.
cc @sekharvajjhala

**Comment by ptyagii** [comment]
The issue has been resolved; thanks, @mayorova deleted logs/* folder from apicast-3.0.0/apicast/ and started again as normal user.

**Comment by mikz** [comment]
@ptyagii close the issue then?
