### ISSUE TITLE
500 error when providing app_key without app_id

### ISSUE THREAD

**Issue by doctorray117** [3scale/apicast#395]
When apicast is set up to authenticate with the keypair of app_id and app_key, providing the app_key without the app_id causes a lua abort and returns a 500 error to client.  

##### Version
CentOS Linux release 7.3.1611 (Core)
nginx version: openresty/1.11.2.3
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled
(configure arguments removed but will be supplied upon request)

##### Steps To Reproduce

curl -v https://api.example.com/api/v1/abc/def/ghi/5?app_key=abcdefghijklmnopqrstuvwxyz

##### Current Result
500 Internal Server Error

##### Expected Result
403 Authentication failed or 403 Authentication parameters missing

##### Additional Information
Relevant log lines:
2017/07/24 22:00:09 [error] 9534#9534: *221532 lua entry thread aborted: runtime error: /usr/local/apicast-3.0.0/apicast/src/proxy.lua:347: attempt to use a non-string key in the "args" option table
stack traceback:
coroutine 0:
        [C]: in function 'encode_args'
        /usr/local/apicast-3.0.0/apicast/src/proxy.lua:347: in function 'access'
        /usr/local/apicast-3.0.0/apicast/src/apicast.lua:103: in function 'access'
        access_by_lua(apicast.conf:77):1: in function <access_by_lua(apicast.conf:77):1>, client: 10.0.0.192, server: _, request: "GET /api/v1/abc/def/ghi/5?app_key=abcdefghijklmnopqrstuvwxyz HTTP/1.1", host: "api.example.com"

**Comment by doctorray117** [comment]
I'm sorry, even though it can be inferred from the log message, I forgot to specify that this is with apicast 3.0.0 release. Thanks.

**Comment by mikz** [comment]
@doctorray117 thanks for the report. I can see the issue and plan to fix it in the next release.
