### ISSUE TITLE
Ability to slot Nginx Custom Configuration in when building Nginx on Openshift

### ISSUE THREAD

**Issue by tnscorcoran** [3scale/apicast#47]
Close to 100% of large complex on-boardings require some degree of customization of their Nginx configuration. Typically, changes are required around the server and location blocks inside Nginx.conf. Lua is less subject to change, though we frequently need to modify that as well. Anything from 
-using URL Path to dictate which Service is used to 
-adding custom headers to 
-adding custom paths to IDP Servers to
-JWT validation etc.

Nginx Openshift needs a back door to slot in custom configuration.

**Comment by mikz** [comment]
It already works. Just mount whatever component want in `/opt/app/sites.d/`. All configs in that folder will be executed in `http` block: https://github.com/3scale/docker-gateway/blob/f68680c1868cea3c6e0fcdfb024f47958f95f303/conf/nginx.conf#L66

For customizing lua we will offer very similar way. Just mount lua file with `_M.setup` method defined and probably set an ENV variable pointing to it. 

We can go into the detail of how to exactly implement those customizations and probably start some example collection.

**Comment by tnscorcoran** [comment]
OK good. Presumably this modifies the image the instance is built from, as opposed to modifying a running instance?

**Comment by mikz** [comment]
Not really. It mounts more files to the stock image provided by us.

**Comment by mikz** [comment]
https://github.com/3scale/docker-gateway/pull/62 shows how to mount files in docker to create new servers.

**Comment by andrewdavidmackenzie** [comment]
See these pending pull requests for custom config.

https://github.com/3scale/apicast/pull/140
https://github.com/3scale/apicast/pull/141
https://github.com/3scale/apicast/pull/144

If you want to do this with OpenShift you will have to build a new docker image, publish it and then change your OpenShift template to refer to your custom DockerImage
