### ISSUE TITLE
Adapt CORS policy to new policy chain system

### ISSUE THREAD

**Issue by davidor** [3scale/apicast#484]
We need to adapt the current CORS module https://github.com/3scale/apicast/blob/3.1-stable/examples/cors/cors.lua

**Comment by davidor** [comment]
@mikz I took a look at the current cors module and I saw that when it receives a CORS request it sets up some headers in the rewrite phase and returns https://github.com/3scale/apicast/blob/a6226ec85b409a249e25af051248777c1edba37f/examples/cors/cors.lua#L47

Shouldn't it proxy the request to the upstream API?

**Comment by mikz** [comment]
@davidor the preflight request is not sent upstream. It just instructs the browser it can make a real request that will go through.

Would be cool to try the blackbox testing #474 on this new policy.
