### ISSUE TITLE
Discussion forum/community

### ISSUE THREAD

**Issue by 4integration** [3scale/apicast#491]
Hi,

This is not an issue (sorry about that) but just wanted to mention that I am missing a active community/forum around 3Scale API Management so I created a Google Group and hope it will come alive :)

https://groups.google.com/forum/#!forum/3scale-api-management-by-red-hat 

/ Joacim Järkeborn

**Comment by andrewdavidmackenzie** [comment]
Hi Joacim. Did you intend the group to cover all of 3scale API Management, or be focussed more on this project/area: the API Gateway? Just out of interest.

**Comment by 4integration** [comment]
Hi Andrew 

My thinking was to cover both, overall 3Scale API Management solution but also its individual components like API Gateway/apicast.
The reason is that I haven't found any good discussion forums for the solution/components involved.
If the forum gets very active it can be an idea to split it :)

FYI I have made two posts in the group ;-)
@andrewdavidmackenzie 

Regards Joacim

**Comment by pimg** [comment]
Seems like a nice initiative Joacim! I can imagine not all questions are suited as github issues. 

I answered 2 questions btw :)

**Comment by davidor** [comment]
Closing as there is nothing else to do in this issue.
