### ISSUE TITLE
Inconsistent env var names with OS template names

### ISSUE THREAD

**Issue by kevprice83** [3scale/apicast#548]
I think we should have more consistency between the APIcast env var names and the openshift template param names.

For example: [APICAST_SERVICES](https://github.com/3scale/apicast/blob/master/doc/parameters.md#apicast_services) should be `APICAST_SERVICES_LIST` to be consistent with the [template equivalent](https://github.com/3scale/apicast/blob/master/openshift/apicast-template.yml#L40)

Do we want to do this for other parameters? All the parameters? At least wherever it makes sense we should.

**Comment by mikz** [comment]
@kevprice83 APIcast OpenShift template intentionally strips `APICAST_` from params, because it is APIcast template.

**Comment by mikz** [comment]
And as for renaming env  like `APICAST_SERVICES` to `APICAST_SERVICES_LIST` (To match OpenShift's SERVICES_LIST) we would have to do it in backwards compatible manner and we don't really want to do it know.

Renaming OpenShift params could break tooling and I'm not sure how that can be done in backwards compatible way.

Contibutions welcome

**Comment by kevprice83** [comment]
I understand the reasoning @mikz, is it really necessary to provide backwards compatibility at this stage? Can we only keep "breaking changes" to major releases then? I have already submitted a [PR](https://github.com/3scale/apicast/pull/549) is that the kind of help you're looking for?

**Comment by mikz** [comment]
@kevprice83 yes we have to provide backwards compatibility. We do it for other things and this should be no exception. We are not going to break QE tooling just because of a rename.

That PR changes just documentation. I'm looking for help with doing the whole rename, including the code and the backwards compatibility. That includes deprecation warnings on use of the old variables.

**Comment by kevprice83** [comment]
Okay understood, I'll see what I can do then @mikz

**Comment by kevprice83** [comment]
@mikz I've added what I think are the necessary changes to the code in #549 and to the unit tests. I haven't added anything for the nginx tests yet because seems there is a problem with my cpan version.

Anyway can you just let me know if this is what you were looking for in terms of a contribution regarding the change I'm suggesting. Just want to know if I'm going in the right direction or not. If you really would rather not introduce this change until the next major release then that's absolutely fine of course. i'm just looking to contribute anything useful/helpful.

**Comment by mikz** [comment]
@kevprice83 that change looks ok. Last part should be a deprecation warning when someone uses the old variable so we can remove it in the 3.3 release.

**Comment by kevprice83** [comment]
Where should I be adding a deprecation warning? A comment in the code? A print out to the logs? Or simply in the changelog?

**Comment by mikz** [comment]
Print out in the logs when the variable is used. And of course it needs to be in the changelog.
