### ISSUE TITLE
No Mapping Rule matched !!!!

### ISSUE THREAD

**Issue by richcoto** [3scale/apicast#557]
I'm receiving a 'No Mapping Rule matched' in my 3scale configuration, and i have no idea why.

In 3scale i added the matching method as this:

POST
/api/v1/addresses/validator

In my api application the endpoint is accesed as follows:

https://mysite/api/v1/addresses/validator

I have other methods working like /api/v1/applications but this new endpoint that i'm trying to add doesn't work i have try everything.

**Comment by mikz** [comment]
To help you debug this, could you:

* configure your API to use `echo-api.3scale.net`,
* increase the APIcast log level to debug (`APICAST_LOG_LEVEL=debug` env variable), 
* share the curl in with `-v` (so I can see both the request and the response),
* share the apicast log,
* strip private data from the log/request.

**Comment by richcoto** [comment]
Thanks mikz, ok there are a few things i need to understand.

you said 'configure your API to use echo-api.3scale.net, i do this in integration / configuration of staging environment, and i specify that in staging base url, so my question is, isn't that base url the api where apicast is going to ask for the endpoints, if i put echo-api.3scalet.net there, how is my api going to be called ?

i wonder where do i specify APICAST_LOG_LEVEL=debug env variable ?

where i can see the apicast log

**Comment by mikz** [comment]
@richcoto closing this as there is not much we can do.
Feel free to reopen this issue if you can provide steps to reproduce and example configuration as described in the issue template.
