### ISSUE TITLE
Include name, summary, and description in policy manifests

### ISSUE THREAD

**Issue by davidor** [3scale/apicast#614]
Currently, manifests include `name` and `description` among other fields, but no `summary`.

The problem is that some descriptions are too long and that can be a problem when showing them in a UI. Let's include a summary which should be a summary of the description. This way, UI designers would be to able to choose between summary or description according to the space available.

@thomasmaas What do you think should be the max length for `summary` ?

**Comment by thomasmaas** [comment]
Not sure if should enforce a max length (ruby gems seems not to enforce for example) but a max length might be 75 characters.
