### ISSUE TITLE
Parsing Error 'resolv.conf' file

### ISSUE THREAD

**Issue by maneta** [3scale/apicast#630]
From expanding the tests on the PR #618 we have found several issues with `parse_nameservers` function in the `gateway/src/resty/resolver.lua` file.

##### Identified Problems

1. The bellow expression will do not catch the case where `server == resolver` because the function `to.string` of the meta table `resolver` is concatenating `"serverName_ip".."ServerNamePort"`

```lua
    if server and server ~= resolver then
      insert(nameservers, nameserver.new(server))
    end
```

2. The parsing of `search local.domain #foobar` brakes the regex

Those are the identified cases I found that brakes the resolver. Maybe should extend a bit the test cases.

##### To Do:
- [x] correct `server == resolver` case
- [ ] correct parsing `search local.domain #foobar`

**Comment by mikz** [comment]
Fixed by #618, #635, #636
