### ISSUE TITLE
Make access_log location customizable

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#650]
The `access_log` directive is currently [set](https://github.com/3scale/apicast/blob/c9df38cf6d9770672e6e6451a4125bc802c5a54a/gateway/conf/nginx.conf.liquid#L95) to `/dev/stdout` and can't be changed.

This enhancement request is to allow customizing the location of the `access_log`, for example with an environment variable, in a similar way `error_log` can be set using `APICAST_LOG_FILE` env var.

**Comment by mikz** [comment]
This is going to happen in the next release (3.3) with log format customization.
But feel free to open a PR to contribute it sooner.
