### ISSUE TITLE
Improve access logging

### ISSUE THREAD

**Issue by mikz** [3scale/APIcast#712]
# Use Cases

- [ ] Customize access log format per service (some custom format or JSON for example, liquid templating).
- [x] Ability to disable access log conditionally per service. (https://github.com/3scale/apicast/pull/856)
- [x] Ship logs to syslog. (https://github.com/3scale/apicast/pull/858)
- [x] Configure location of the access log file (for native deployments). (closes https://github.com/3scale/apicast/issues/650)

# Details

[`access_log`](http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log) directive offers `if` to enable/disable logging by setting a variable to 0/1 - this can be used to enable/disable logging by a policy.

It is possible the `path` parameter of the `access_log` directive can be a variable too and can be controlled from within a policy. Then we should consider using [`open_log_file_cache` ](http://nginx.org/en/docs/http/ngx_http_log_module.html#open_log_file_cache) to files opened.

Syslog can be either achieved by setting `syslog:` path to the `access_log` directive, or we have to reuse https://github.com/nmasse-itix/apicast-logger to offer syslog from a policy.

Custom formats can be defined by [`log_format`](http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) directive pointing just to a variable that is later populated by a policy.

**Comment by mayorova** [comment]
@mikz looks like this would cover https://github.com/3scale/apicast/issues/650 as well?  ("_Configure location of the access log file (for native deployments)._" part)

**Comment by mikz** [comment]
@mayorova Indeed.

**Comment by mikz** [comment]
Conclusion from my research:

1) syslog has to be set when the gateway starts and is global for all services. So it either logs to a file (stdout) or syslog.

2) Logging format can be customized, but it is pretty unpredictable because of nginx escaping the result. This can be turned off in nginx `1.13.10` but we have `1.13.6`. We would have to wait for next OpenResty release to properly support this.

3) We can enable/disable logging per service easily.

**Comment by davidor** [comment]
So, regarding the format, we decided to wait for the next release of OpenResty (see @mikz comment above). Enabling/Disabling the service can be done with the policy introduced in #856 , and APIcast can be configured to log to syslog using an ENV.

I think there's nothing else we need to do for 2.3, so I'll remove this issue from the milestone. cc/ @andreumasferrer

**Comment by andreumasferrer** [comment]
ACK. Will update [THREESCALE-1148](https://issues.jboss.org/browse/THREESCALE-1148) accordingly.

**Comment by raghubanda** [comment]
hi @mikz  Is it possible to expect this feature as a policy?

**Comment by davidor** [comment]
Done in https://github.com/3scale/APIcast/pull/1089
