### ISSUE TITLE
Apicast in Docker and Logging

### ISSUE THREAD

**Issue by 4integration** [3scale/apicast#753]
Hi,

I am running Apicast in Docker container it would be easier to have it in /var/log at Docker host.
Anything special to think of?

Is it just to configure:
```
APICAST_LOG_FILE=/var/log/apicast/error.log
APICAST_ACCESS_LOG_FILE=/var/log/apicast/access.log
```

and then mount directory to Docker host?
`-v /var/log/apicast:/var/log/apicast 
`
/ Joacim

**Comment by mikz** [comment]
Common Docker deployment practice is to just use STDOUT/STDERR and then `docker logs` or use some logging plugins.

But yes, what you wrote should work.

**Comment by mikz** [comment]
Closing this. Feel free to reopen if there is actually some issue with it.
