### ISSUE TITLE
Rename to APIcast

### ISSUE THREAD

**Issue by mikz** [3scale/apicast#77]
Let's rename this repository to APIcast.

- [ ] rename this repository to `apicast`
- [ ] rename `quay.io/3scale/gateway` to `quay.io/3scale/apicast` ?

@vramosp do you agree?

**Comment by andrewdavidmackenzie** [comment]
Should update any references to the repo in our tutorial referring to it also:

https://support.3scale.net/guides/infrastructure/docker-openshift

Such as step 3:

<img width="599" alt="screen shot 2016-09-20 at 11 03 44" src="https://cloud.githubusercontent.com/assets/5529132/18664226/f0fdd5e4-7f21-11e6-8a41-77818de15651.png">

But a complete review of that article is best done to catch other mentions, and change text references to "docker-gateway" to "apicast" or "APIcast" also.

@vramosp want to create a separate issue for the documentation change in the docs repo?

**Comment by mikz** [comment]
The links would not stop working (GitHub provides redirects), but yes, we should change them.
