### ISSUE TITLE
Redis Sentinel

### ISSUE THREAD

**Issue by y-tabata** [3scale/APIcast#806]
## Requirements

Since Redis is more used, for example by the `rate limit` policy, we have to consider to protect Redis. Generally, Redis Sentinel is useful for high availability, so APIcast need to be able to use Redis Sentinel same like apisonator. The `lua-resty-redis` does not support Redis Sentinel, however I found the [`lua-resty-redis-connector`](https://github.com/pintsized/lua-resty-redis-connector) supports Redis Sentinel. We need to consider it is usable or not.

**Comment by y-tabata** [comment]
Before implementing this, we need to prepare a Redis Sentinel in the test environment and create environment variables to specify "sentinel hosts", "sentinel role" and "sentinel group name".

**Comment by andrewdavidmackenzie** [comment]
We don't plan to invest in the OAuth2 scenario that requires a shared token store with redis, instead promoting OIDC flow. So, we will close this issue.
