### ISSUE TITLE
Liquid tags are not working properly and can cause failure of the Apicast

### ISSUE THREAD

**Issue by pestanko** [3scale/apicast#828]
When using liquid tags in the policies for example: `url_rewrite` or `header_policy` apicast is not able to resolve this liquid values.

Here are the logs:
- Apicast: http://pastebin.test.redhat.com/625140
- with debug: http://pastebin.test.redhat.com/625141

##### Version

Built from the master branch. 

##### Steps To Reproduce

1. Create new service with headers policy
2. Set value for a header for example: `Service_id {{ service.id }}`
3. Save and get an error: 500 Internal server error
4. Each other request will cause the `failed to acquire lock to lazy load`

Here is a sandbox config: http://pastebin.test.redhat.com/625156 (Service with id 2)

##### Additional Information

It was staging gateway with lazy loading.
Configuration: 2.2-GA with apicast built from the master (30-07-2018)

**Source Commit:** Merge pull request #820 from 3scale/conditional-policy-docs ab474ec authored by David Ortiz

The issue has been discussed with @davidor on Slack.

**Comment by davidor** [comment]
I tried using the same policy chain and the `THREESCALE_CONFIG_FILE` env, and couldn't reproduce the error:
```json
        "policy_chain": [
          {
            "name": "apicast",
            "version": "builtin",
            "configuration": {}
          },
          {
            "name": "url_rewriting",
            "version": "builtin",
            "configuration": {
              "query_args_commands": [
                {
                  "op": "set",
                  "arg": "new_arg",
                  "value_type": "liquid",
                  "value": "{{ service.id }}"
                }
              ]
            }
          }
        ],
```

So this might only happen when using `THREESCALE_PORTAL_ENDPOINT`. I'll need to investigate a bit more.

**Comment by pestanko** [comment]
@davidor Hi, you could try to reproduce this issue on our cluster - that is from today available in the project **3scale**.
