### ISSUE TITLE
[rate-limit] redis_url with empty value or null value results in Internal server error

### ISSUE THREAD

**Issue by jsmadis** [3scale/apicast#834]
Policy created via API with redis_url value **''** (empty string) or null results in internal server error (status code 500).

### Empty string: 
**body message:**
> failed to connect to redis on 127.0.0.1:6379: connection refused

**Policy chain from apicast config:**

`"policy_chain":[{"name":"apicast","version":"builtin","configuration":{}},{"name":"rate_limit","version":"builtin","configuration":{"limits_exceeded_error":{"status_code":429,"error_handling":"exit"},"configuration_error":{"status_code":500,"error_handling":"exit"},"redis_url":"","fixed_window_limiters":[{"window":30,"key":{"scope":"service","name":"fixed_window","name_type":"plain"},"count":5}]}}]`

### Null:
**body message:**

`<html> <head><title>500 Internal Server Error</title></head> <body bgcolor="white"> <center><h1>500 Internal Server Error</h1></center> <hr><center>openresty/1.13.6.2</center> </body> </html>
`

**Policy chain from apicast config:**
`"policy_chain":[{"name":"apicast","version":"builtin","configuration":{}},{"name":"rate_limit","version":"builtin","configuration":{"limits_exceeded_error":{"status_code":429,"error_handling":"exit"},"configuration_error":{"status_code":500,"error_handling":"exit"},"redis_url":null,"fixed_window_limiters":[{"window":30,"key":{"scope":"service","name":"fixed_window","name_type":"plain"},"count":5}]}}]`

**Comment by mikz** [comment]
I agree that empty value should be ignored and not default to localhost.

**Comment by jsmadis** [comment]
redis_url with correct value is ignored and apicast is trying to connect to localhost.

> Test request failed with HTTP code 500: failed to connect to redis on 127.0.0.1:6379: connection refused

**Policy chain from apicast config:**

`"policy_chain":[{"name":"apicast","version":"builtin","configuration":{}},{"name":"rate_limit","version":"builtin","configuration":{"limits_exceeded_error":{"status_code":429,"error_handling":"exit"},"configuration_error":{"status_code":500,"error_handling":"exit"},"fixed_window_limiters":[{"window":30,"key":{"scope":"global","name":"fixed_window","name_type":"plain"},"count":5}],"redis_url":"https://jsmadis-redis.example.com:6379"}}]`
