### ISSUE TITLE
Which version of Lua for Apicast ?

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/apicast#846]
Hello,

With @lucamaf, we are trying to install a development environment to be able to develop policies for APIcast.

We are having difficult times trying to install such environment. 

Namely, if I install the latest version of lua (5.3), the `make dependencies` fails because of a missing `ffi` module that is only present in LuaJIT:

```
lua-rover scm-1 is now installed in /home/redhat/git/apicast/lua_modules (license: Apache-2.0)

lua_modules/bin/rover install --roverfile=gateway/Roverfile
/usr/bin/lua: lua_modules/share/lua/5.3/rover/exec.lua:1: module 'ffi' not found:No LuaRocks module found for ffi
	no field package.preload['ffi']
	no file 'lua_modules/share/lua/5.3/ffi.lua'
	no file 'lua_modules/share/lua/5.3/ffi/init.lua'
	no file '/usr/share/lua/5.3/ffi.lua'
	no file '/usr/share/lua/5.3/ffi/init.lua'
	no file '/usr/lib64/lua/5.3/ffi.lua'
	no file '/usr/lib64/lua/5.3/ffi/init.lua'
	no file './ffi.lua'
	no file './ffi/init.lua'
	no file '/home/redhat/.luarocks/share/lua/5.3/ffi.lua'
	no file '/home/redhat/.luarocks/share/lua/5.3/ffi/init.lua'
	no file '/usr/local/share/lua/5.3/ffi.lua'
	no file '/usr/local/share/lua/5.3/ffi/init.lua'
	no file 'lua_modules/lib/lua/5.3/ffi.so'
	no file '/usr/lib64/lua/5.3/ffi.so'
	no file '/usr/lib64/lua/5.3/loadall.so'
	no file './ffi.so'
	no file '/home/redhat/.luarocks/lib/lua/5.3/ffi.so'
	no file '/usr/local/lib/lua/5.3/ffi.so'
```

And if I install LuaJIT instead (that has the `ffi` module), Apicast cannot start because rover is using a feature of Lua 5.2 (`__pairs` in the metatable) and LuaJIT is still on Lua 5.1. 

Question: should we install Lua or LuaJIT ? In which version ? 

Thanks for your help !

**Comment by mikz** [comment]
APIcast works only with OpenResty, not with plain Lua or LuaJIT.

We provide docker images https://github.com/3scale/s2i-openresty and docker development environment https://github.com/3scale/apicast#development-using-docker

Setting up local environment can be challenging and definitely is recommended only for experienced OpenResty hackers.

**Comment by tlefevre** [comment]
OpenResty comes with LuaJit - I suggest you use that. That's what I had the best of luck with. I originally started with 5.3, then downgraded to 5.2 and got to a point where it specifically went splat because it needed 5.1.

**Comment by davidor** [comment]
The question has been answered by @mikz , so closing this issue.
