### ISSUE TITLE
3.2-Stable Development Image - Apicast gateway not starting when following the guide

### ISSUE THREAD

**Issue by tlefevre** [3scale/APIcast#851]
I have run make development on the 3.2-stable branch and am trying to run the apicast gateway policies example with the following command

bin/apicast -c examples/policies/example.json -b --policy-load-path examples/policies -v

It explodes in a bunch of errors. 

##### Version

My local system:
Linux 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

docker-compose -v
docker-compose version 1.22.0, build f46880fe

docker -v
Docker version 18.06.0-ce, build 0ffa825

The docker image:

bash-4.2$ nginx -V
bash: nginx: command not found
bash-4.2$ openresty -V
nginx version: openresty/1.13.6.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with OpenSSL 1.1.0h  27 Mar 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.13 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.5 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-dtrace-probes --with-stream --with-stream_ssl_module --with-http_ssl_module

I'm guessing it doesn't make much sense to print the timestamp of a container image that is made with the `make development` command.

##### Steps To Reproduce

1. git clone apicast-repo && cd repo
2. make development
3. bin/apicast -c examples/policies/example.json -b --policy-load-path examples/policies -v

##### Current Result

bash-4.2$ pwd
/home/centos
bash-4.2$ bin/apicast -c examples/policies/example.json -b --policy-load-path examples/policies -v
ERROR: /home/centos/gateway/src/apicast/balancer.lua:2: module 'resty.url' not found:No LuaRocks module found for resty.url
	no field package.preload['resty.url']
	no file '/home/centos/gateway/src/resty/url.lua'
	no file '/usr/local/openresty/site/lualib/resty/url.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/url/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/url.ljbc'
	no file '/usr/local/openresty/lualib/resty/url/init.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/url.lua'
	no file '/usr/local/openresty/site/lualib/resty/url/init.lua'
	no file '/usr/local/openresty/lualib/resty/url.lua'
	no file '/usr/local/openresty/lualib/resty/url/init.lua'
	no file './lua_modules/share/lua/5.1/resty/url.lua'
	no file './lua_modules/share/lua/5.1/resty/url/init.lua'
	no file './resty/url.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/url.lua'
	no file '/usr/local/share/lua/5.1/resty/url.lua'
	no file '/usr/local/share/lua/5.1/resty/url/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/url.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/url/init.lua'
	no file '/home/centos/lua_modules/share/lua/5.1/resty/url.lua'
	no file '/home/centos/lua_modules/share/lua/5.1/resty/url/init.lua'
	no file '/usr/local/openresty/lualib/resty/url.ljbc'
	no file '/usr/local/openresty/lualib/resty/url/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/url.lua'
	no file '/usr/local/openresty/lualib/resty/url/init.lua'
	no file '/home/centos/gateway/src/resty/url.so'
	no file '/usr/local/openresty/site/lualib/resty/url.so'
	no file '/usr/local/openresty/lualib/resty/url.so'
	no file '/home/centos/gateway/lib/resty/url.so'
	no file './lua_modules/lib/lua/5.1/resty/url.so'
	no file './resty/url.so'
	no file '/usr/local/lib/lua/5.1/resty/url.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/url.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/centos/lua_modules/lib/lua/5.1/resty/url.so'
	no file '/home/centos/gateway/src/resty.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file '/home/centos/gateway/lib/resty.so'
	no file './lua_modules/lib/lua/5.1/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/centos/lua_modules/lib/lua/5.1/resty.so'
	no file '/home/centos/gateway/src/apicast/resty/url.lua'
	no file '/usr/local/openresty/site/lualib/apicast/resty/url.ljbc'
	no file '/usr/local/openresty/site/lualib/apicast/resty/url/init.ljbc'
	no file '/usr/local/openresty/lualib/apicast/resty/url.ljbc'
	no file '/usr/local/openresty/lualib/apicast/resty/url/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apicast/resty/url.lua'
	no file '/usr/local/openresty/site/lualib/apicast/resty/url/init.lua'
	no file '/usr/local/openresty/lualib/apicast/resty/url.lua'
	no file '/usr/local/openresty/lualib/apicast/resty/url/init.lua'
	no file './lua_modules/share/lua/5.1/apicast/resty/url.lua'
	no file './lua_modules/share/lua/5.1/apicast/resty/url/init.lua'
	no file './apicast/resty/url.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apicast/resty/url.lua'
	no file '/usr/local/share/lua/5.1/apicast/resty/url.lua'
	no file '/usr/local/share/lua/5.1/apicast/resty/url/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apicast/resty/url.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apicast/resty/url/init.lua'
	no file '/home/centos/lua_modules/share/lua/5.1/apicast/resty/url.lua'
	no file '/home/centos/lua_modules/share/lua/5.1/apicast/resty/url/init.lua'
	no file '/usr/local/openresty/lualib/apicast/resty/url.ljbc'
	no file '/usr/local/openresty/lualib/apicast/resty/url/init.ljbc'
	no file '/usr/local/openresty/lualib/apicast/resty/url.lua'
	no file '/usr/local/openresty/lualib/apicast/resty/url/init.lua'
stack traceback:
	/home/centos/gateway/src/apicast/balancer.lua:2: in main chunk
	[C]: in function 'root_require'
	/home/centos/gateway/src/resty/sandbox.lua:43: in function 'fallback'
	/home/centos/gateway/src/resty/sandbox.lua:107: in function 'require'
	/home/centos/gateway/src/apicast/policy/apicast/apicast.lua:1: in function 'loader'
	/home/centos/gateway/src/resty/sandbox.lua:104: in function 'loader'
	/home/centos/gateway/src/resty/sandbox.lua:104: in function 'loader'
	/home/centos/gateway/src/apicast/policy_loader.lua:144: in function 'policy_loader'
	/home/centos/gateway/src/apicast/policy_chain.lua:85: in function 'load_policy'
	/home/centos/gateway/src/apicast/policy_chain.lua:52: in function 'build'
	/home/centos/gateway/src/apicast/policy_chain.lua:163: in main chunk
	[C]: in function 'require'
	/home/centos/gateway/src/apicast/executor.lua:9: in main chunk
	[C]: in function 'require'
	/tmp/kfeWd2uYLw:55: in function 'file_gen'
	init_worker_by_lua:53: in function <init_worker_by_lua:51>
	[C]: in function 'xpcall'
	init_worker_by_lua:60: in function <init_worker_by_lua:58>

##### Expected Result

That the apicast gateway starts.

##### Additional Information

I have tried running make dependencies just for kicks, but that gives me this:

bash-4.2$ make dependencies
/usr/local/openresty/luajit/bin/rover install --roverfile=gateway/Roverfile
ERROR: /usr/local/openresty/luajit/share/lua/5.1/rover/install.lua:31: Your user does not have write permissions in /home/centos/./lua_modules/luarocks/rocks 
-- you may want to run as a privileged user or use your local tree with --local.
stack traceback:
	/usr/local/openresty/luajit/share/lua/5.1/rover/install.lua:31: in function 'install'
	/usr/local/openresty/luajit/share/lua/5.1/rover/install.lua:77: in function 'call'
	...cal/openresty/luajit/share/lua/5.1/rover/cli/install.lua:41: in function <...cal/openresty/luajit/share/lua/5.1/rover/cli/install.lua:19>
	/usr/local/openresty/luajit/share/lua/5.1/rover/cli.lua:33: in function </usr/local/openresty/luajit/share/lua/5.1/rover/cli.lua:27>
	...penresty/luajit/luarocks/rocks/lua-rover/scm-1/bin/rover:3: in function 'file_gen'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
	[C]: in function 'xpcall'
	init_worker_by_lua:62: in function <init_worker_by_lua:60>
make: *** [dependencies] Error 1

**Comment by davidor** [comment]
There have been a few changes in the development image, for example #1052 and #1067 
Please let us know if you still have issues with the image generated from the master branch.
