### ISSUE TITLE
Master Development Image - Apicast gateway not starting when following the guide

### ISSUE THREAD

**Issue by tlefevre** [3scale/APIcast#852]
The guide says to run 'make development' and it will create a docker with everything set up. That's not correct however, it lacks the dependencies that you have to install yourself.

##### Steps To Reproduce

1. make development
2. bin/apicast -c aftale-modul/config/aftale-modul.json -b --policy-load-path gateway/src/apicast/policy -v

##### Current Result

bash-4.2$ bin/apicast -c aftale-modul/config/aftale-modul.json -b --policy-load-path gateway/src/apicast/policy -v
ERROR: /home/centos/gateway/src/apicast/policy_loader.lua:21: module 'resty.env' not found:No LuaRocks module found for resty.env
	no field package.preload['resty.env']
	no file '/home/centos/gateway/src/resty/env.lua'
	no file '/usr/local/openresty/site/lualib/resty/env.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/env/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/env.ljbc'
	no file '/usr/local/openresty/lualib/resty/env/init.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/env.lua'
	no file '/usr/local/openresty/site/lualib/resty/env/init.lua'
	no file '/usr/local/openresty/lualib/resty/env.lua'
	no file '/usr/local/openresty/lualib/resty/env/init.lua'
	no file './lua_modules/share/lua/5.1/resty/env.lua'
	no file './lua_modules/share/lua/5.1/resty/env/init.lua'
	no file './resty/env.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/env.lua'
	no file '/usr/local/share/lua/5.1/resty/env.lua'
	no file '/usr/local/share/lua/5.1/resty/env/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/env.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/env/init.lua'
	no file '/home/centos/lua_modules/share/lua/5.1/resty/env.lua'
	no file '/home/centos/lua_modules/share/lua/5.1/resty/env/init.lua'
	no file '/usr/local/openresty/lualib/resty/env.ljbc'
	no file '/usr/local/openresty/lualib/resty/env/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/env.lua'
	no file '/usr/local/openresty/lualib/resty/env/init.lua'
	no file '/home/centos/gateway/src/resty/env.so'
	no file '/usr/local/openresty/site/lualib/resty/env.so'
	no file '/usr/local/openresty/lualib/resty/env.so'
	no file '/home/centos/gateway/lib/resty/env.so'
	no file './lua_modules/lib/lua/5.1/resty/env.so'
	no file './resty/env.so'
	no file '/usr/local/lib/lua/5.1/resty/env.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/env.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/centos/lua_modules/lib/lua/5.1/resty/env.so'
	no file '/home/centos/gateway/src/resty.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file '/home/centos/gateway/lib/resty.so'
	no file './lua_modules/lib/lua/5.1/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/centos/lua_modules/lib/lua/5.1/resty.so'
stack traceback:
	/home/centos/gateway/src/apicast/policy_loader.lua:21: in main chunk
	[C]: in function 'require'
	/home/centos/gateway/src/apicast/loader.lua:14: in main chunk
	[C]: in function 'require'
	/home/centos/gateway/src/apicast/executor.lua:7: in main chunk
	[C]: in function 'require'
	/tmp/v1aUWaP8hm:55: in function 'file_gen'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
	[C]: in function 'xpcall'
	init_worker_by_lua:62: in function <init_worker_by_lua:60>

##### Expected Result

The api-cast gateway starts up. 

##### Additional Information

If you make sure to run "make dependencies" inside the container, it'll work just fine. The README needs to be updated to indicate this.

Master says to run "make lua_modules" instead of "make dependencies", but if you run the lua_modules target it will just say the lua_modules are up to date even though no luarocks were installed in lua_modules and the directory is completely empty.

**Comment by tlefevre** [comment]
Actually I was wrong - make dependencies does indeed install quite a few things, but it's not enough. 

rover install --roverfile=gateway/Roverfile

This is what actually installs the luarocks and makes the APICast gateway able to start.

**Comment by davidor** [comment]
This should be fixed by #1052
