### ISSUE TITLE
Referrer filter policy is accepting a request that should be filtered

### ISSUE THREAD

**Issue by pestanko** [3scale/apicast#875]
Referrer filter is accepting a request with a different `Referer` filter that is not allowed.

##### Version
- Apicast 3.3-ER1

##### Steps To Reproduce

1. Configure and enable referrer filter policy
2. Set referrer filters for the application
3. Make a request with `Referer` header that is allowed
4. Make a request with `Referer` header that is not allowed - it should fail
5. Make a request with `Referer` header that is not allowed and it will fail (that is OK)

##### Current Result
- I send the first request with valid referrer header
- Second with invalid (not in filters), but it will pass
- Each next invalid header will fail on 403

##### Expected Result
So expected behavior in your case:
- 1st with valid referrer => Accept
- 2nd with invalid referrer => Deny
- 3rd with invalid referrer => Deny

**Comment by davidor** [comment]
Fixed in #877
