### ISSUE TITLE
apicast debug policy specification

### ISSUE THREAD

**Issue by mkudlej** [3scale/apicast#883]
I've used 
```
User-Agent: APIcast/3.3.0-beta2 (Linux; x64; env:sandbox) APIcast/3.3.0-beta2
```
and I've realized after @davidor advise that *debug policy* should be in policy chain before *apicast policy*. 
It will be great to have this info about *debug policy* placement in policy chain in *debug policy* specification(https://github.com/3scale/apicast/blob/master/gateway/src/apicast/policy/liquid_context_debug/apicast-policy.json) , so user can read it in UI.

Also if there is any other policy like *upstream policy* which should be in policy chain before *apicast policy* it should be written also in its description.

**Comment by davidor** [comment]
Fixed in #886
