### ISSUE TITLE
Keycloak role check policy - only whitelisted resources (endpoints) are allowed

### ISSUE THREAD

**Issue by mayorova** [3scale/APIcast#889]
I noticed the following behavior in the current implementation of the Keycloak role check policy:

It looks like when "whitelist" type is used, ALL endpoints you have configured would need to have rules defined, otherwise authorization fails.

For example, if I have a number of endpoints endpoints, say, `/one`, `/two`, `/three`, and I don't care about roles for these ones - I just authorize normally (using mapping rules and rate limits).
But then I also have `/admin` endpoint for which I want to check if the `admin` role appears in the JWT (as a realm role, for example).

If I configure "whitelist" for resource `/admin` with the realm role `admin`, all other endpoints will fail.
It looks like this is the desired behavior ([spec](https://github.com/3scale/apicast/blob/3.3-stable/spec/policy/keycloak_role_check/keycloak_role_check_spec.lua#L261-L264)). But to me it seems quite limited, as it obliges me to duplicate all mapping rules in the role check policy configuration, even if I don't care about the roles JWT token has for these endpoints.

@y-tabata @tmogi001 Is this how you expect the policy to work?

**Comment by davidor** [comment]
Closing as the doubt was clarified.
