### ISSUE TITLE
[multi tenancy] the influence range at the time of configuring a wrong OIDC issuer.

### ISSUE THREAD

**Issue by y-tabata** [3scale/apicast#910]
[provide a description of the issue]
If a tenant admin configures a wrong OIDC issuer for only 1 service of 1 tenant in the Integration view in 3scale Admin Portal, other tenant admins cannot change their service configurations with the error message "auto-updating configuration failed with: Cannot serialize table: excessively sparse array" in configuration_loader.lua.
After that when we try to redeploy the apicast-production, we fail in deploying with no error message.

##### Version
tag: 3scale-2.2.1

##### Current Behavior
The apicast-production loads all services of all tenants in one time, and if there is a wrong OIDC issuer configuration, the apicast-production fails in loading all services of all tenants.

##### Expected Result
Even if there is a wrong OIDC issuer configuration in 1 tenant, other tenant's admin should be able to change their service configurations.
Or even if there is a wrong OIDC issuer configuration, the apicast-production should load the service configuration successfully.

**Comment by mikz** [comment]
This has been fixed in https://github.com/3scale/apicast/pull/893 and released as [3.3.0-cr1](https://github.com/3scale/apicast/blob/master/CHANGELOG.md#330-cr1---2018-09-14).
