### ISSUE TITLE
Add support for Okta integration

### ISSUE THREAD

**Issue by VinayBhalerao** [3scale/apicast#916]
As part of multiple IDPs support with APIcast, we should be able to integrate Okta.

Okta setup
- Create a free trial account on https://www.okta.com/
- Create an application and add `redirect_uri`
- Create a `user`

Follow Okta documentation on how to create the above https://developer.okta.com/documentation/

For our integration, I have used `implicit grant flow` https://developer.okta.com/authentication-guide/implementing-authentication/implicit

1. Send `/authorize` call to Okta auth server. Example below.

```
https://example.okta.com/oauth2/v1/authorize?client_id=<your_client_id>&response_type=token&scope=openid&redirect_uri=http%3A%2F%2Flocalhost%3
A3000%2Fcallback&state=state-296bc9a0-a2a2-4a57-be1a-d0e2fd9bb601&nonce=foo'
```

2. The auth server redirects to login page. Enter the user credentials.

![redhat-org-166273_-_sign_in](https://user-images.githubusercontent.com/7827135/46121238-c86c6600-c1c7-11e8-8605-6944aea2d5b9.png)

3. The `access_token` is redirected back to the `redirect_uri` of the application. Example below.

```
http://localhost:3000/callback#access_token=eyJraWQiOiJ3UmRQTG0xU294MnIySHNNbTBjcUExcTNyOHhjamNyTzFzaWVSbHBqNG9vIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnIxd293OVVjaE9xM2Y5OXlBb3o3SVdGTU9RZ2prUUNvOU45aXBkZUxadTAiLCJpc3MiOiJodHRwczovL3JlZGhhdC0zc2NhbGUub2t0YS5jb20iLCJhdWQiOiJodHRwczovL3JlZGhhdC0zc2NhbGUub2t0YS5jb20iLCJzdWIiOiIwb2ExdTZ2c3hlTzBkMktldTM1NiIsImlhdCI6MTUzNzkzODcwMiwiZXhwIjoxNTM3OTQyMzAyLCJjaWQiOiIwb2ExdTZ2c3hlTzBkMktldTM1NiIsInVpZCI6IjAwdTF1OHo0NDNCbFpsTHk4MzU2Iiwic2NwIjpbIm9wZW5pZCJdfQ.E9pgfJ8xrgEishu4nEprwtUBzOobB88OAwoGAB48pCGkJXyHYHIMRLFPdD6w86rCGiheUgYUnjAPXm2njjbCSOnKJi79HEl83ohiUzj0YUHMjrw-P_NwVtnnKEVwNw_z5K4_UYbaWDS-Y3vlhunVkOdkISaMH5ezLy1pbkh3sKdG7WKSpQulA9Y0YGzlUUzxsqM-UgCAECyGzQpEiUGRvvTSo4qY-micuQrV7cPHbyEaXJDaWE7QTdgAGrG9JBuv-hy2qbfF2eMfAK-N7mxy0Sh6lRMdU3GhTST1xwKMcbjK9Vn7aH3bljWIuVLnKEw2V21GQfqbTWpLOtJyRWWMqg&token_type=Bearer&expires_in=3600&scope=openid&state=state-296bc9a0-a2a2-4a57-be1a-d0e2fd9bb601
```

**Important links**

- OpenID connect configurations for Okta
https://example.okta.com/.well-known/openid-configuration

- JWKS_URI
https://example.okta.com/oauth2/v1/keys

We can reuse the existing module of Forgerock to verify the incoming `access_token` against the `public_key`.

Let me know if you need any more information.

**Comment by mikz** [comment]
Have you verified this does not work already?

**Comment by VinayBhalerao** [comment]
@mikz The above flow is verified on my test account - yes. If you need access to that, let me know. It will save your setup time.

One thing I couldn't verify is `verification of access_token` since it requires conversion of `jwks to pem` and then `pem to public_key`. I hope it shouldn't be a problem since it's the standard openID provider medata https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata,  and we are already doing that as part of forgerock.

**Comment by mikz** [comment]
@VinayBhalerao APIcast supports JWK, so it should work.

If it does not work, we can try to fix it, but right now I assume it works, because it should.

**Comment by VinayBhalerao** [comment]
I can confirm that Okta integration works. I'll write a post as earlier on how to do the integration step by step. 

The JWK work done is simply awesome <3. Making life much easier :)

Closing the issue.

**Comment by vsriadib** [comment]
can you advise service to service integration using 3scale and OKTA
