### ISSUE TITLE
Handle API errors when getting the configuration from 3scale

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast#98]
Currently when making the call to `/admin/api/nginx/spec.json` the API can return: `{"error":"Access denied"}` in case the access token is not correct, or `{"status":"Not found"}` if the URL is wrong. This body is used to set `provider.contents`.

`download()` and `curl()` in `configuration.lua` should check for the status code of the response and if it's not `200` probably set the `provider.contents` to `null`.

**Comment by mikz** [comment]
Partially fixed in #139. Also curl and the download check for successful status code. Should be done then.
