### ISSUE TITLE
Feature: add ability to stop matching rules after first match

### ISSUE THREAD

**Issue by davidor** [3scale/apicast#980]
The current behavior is that all the mapping rules are matched. If there are several matches, APIcast reports the metrics associated with each rule that matched.

So for example, a request with path `/abc/def`, matches these 2 rules:
```
`/abc` => metric_a + 1
`/abc/def` => metric_b + 1
```

With the current behavior, APIcast reports metric_a + 1 and metric_b + 1.

The request is to be able to specify, for each rule, a new attribute that indicates whether APIcast should stop evaluating more rules if that one matches.

With that new feature, we could specify:
```
`/abc` => metric_a + 1 , last =true
`/abc/def` => metric_b + 1
```

And APIcast would only report metric_a + 1 for a request with path `/abc/def`.

Ref: https://issues.jboss.org/browse/THREESCALE-1344

**Comment by andrewdavidmackenzie** [comment]
Does the "setting" need to specify if "for each rule" or once for the entire "rule set" is enough?
I guess the other one allows for some interesting combinations and covers more cases.

But, before deciding that - I'd close the loop with the UI team, to see if specifying this per rule is what they are considering (I know, they could have one setting, and then add to all rules downloaded - but that seems a waste of implementation effort here).

**Comment by hallelujah** [comment]
We planned to have only each rule but the case of some customers who wants to have it for the whole rule set is probably more common.
We can do it in the UI and set the `last` value to true for every rule when we save the proxy

**Comment by thomasmaas** [comment]
I'd say toggling all could wait for next iteration. It needs good ui with visual feedback (not just a checkbox) and it needs javascript to make that happen. So from a technical perspective makes more sense when mapping rules is a react component (reordering will hopefully make that happen).

**Comment by mikz** [comment]
To be more in line with the URL rewriting policy and proxy server configurations it makes more sense to be per rule.

**Comment by davidor** [comment]
@thomasmaas For me, it's clear that mapping rules should be sortable to make this work.

The question is more about whether we should:
A) Have a "last" attribute for each mapping rule.
B) Have a global setting that applies to the whole set of mapping rules.

For example, with option A) you could have something like this:
```
1) /abc => last = false
2) /def => last = false
3) /def/something => last = true
4) /def/something/else => last = false
```
With those rules, the path `/def` would match the second rule, but `last=false` so it would continue with 3), match it, and stop there because `last=true` for that rule.

**Comment by davidor** [comment]
I agree with @mikz . Also, this approach is more flexible and if we do not want to introduce the complexity of having a boolean per rule in the UI, we could just have a global setting that sets all of them to true/false

**Comment by thomasmaas** [comment]
@davidor i understood and my point was that "setting in the UI to switch them all to 'true'" can wait a bit

**Comment by MarkCheshire** [comment]
From a UX perspective and for the most common use case I would have a single boolean for all mapping rules. If it is easier for implementation to have the boolean per rule, I recommend to keep them as an internal implementation. This detail should be hidden in the UI and instead a single switch turns them all to true or false (and sets the default for new rules or those created by API).

If we get requests to expose this detail in future we can do so.

**Comment by davidor** [comment]
@hallelujah Can we agree on the following for APIcast?

APIcast will expect the `last` attribute per mapping rule even if you choose to have just a global setting in the UI. This will give us more flexibility on the APIcast side for users who use it in stand-alone mode and also possibly for projects like [Ostia](https://github.com/3scale/ostia)

**Comment by hallelujah** [comment]
@davidor Yes we will anyway send all the values anyway in the JSON response
