### ISSUE TITLE
OpenID/OAuth token validation flow in APICast is incorrect

### ISSUE THREAD

**Issue by magnusvage** [3scale/APIcast#988]
I believe that the implemented steps to validate an OpenID/OAuth token are incorrect

Looking at the source code found at https://github.com/3scale/apicast/blob/ab4ce9d08759c657944078ba8dbf1216c533c9da/gateway/src/apicast/oauth/oidc.lua

It explicitly references https://tools.ietf.org/html/rfc7523#section-3, which are the steps of how an AUTHORIZATION server needs to validate a token. However, APICast is not the authorization server, it is the resource server (Or more correctly, acting as a front for several resource servers) if looking at https://tools.ietf.org/html/rfc6749#section-1.1

resource server
      The server hosting the protected resources, capable of accepting
      and responding to protected resource requests using access tokens.

As of now, the aud or azp is taken to be the application client_id (from the source code above):

local app_id = payload.azp or payload.aud

However, APICast should check to opposite: That aud is an identifer of APICast (or even more preferrably and granular, an identifier of the service that is being called).

As described in https://tools.ietf.org/html/rfc7519#section-4.1.3

The "aud" (audience) claim identifies the recipients that the JWT is
   intended for.  Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.

This would require that all services are represented as clients in Keycloak (or any auth server), and that application clients are given access to service clients in the auth server. This is so that when the application requests a token from the auth server (be it a client credentials or authorization code flow), the application can set the scope to the service in the auth request, explicitly requesting access to the service, which is how it was all intended to work.

I am not a super expert with all things OpenID/OAuth, so if I've gotten something terribly wrong and it all works as intended, please feel free to close this.

**Comment by magnusvage** [comment]
To flesh out my reasoning above, I created a scenario.

Two clients exist in Keycloak, representing an application and a service in 3scale. demo-application has no roles/access to demo-service at this point.

<img width="381" alt="screenshot 2019-02-18 at 00 08 44" src="https://user-images.githubusercontent.com/36159342/52920847-72809200-3311-11e9-9f92-986bb164beff.png">

As demo-application, requesting an access token for demo-service does not give me demo-service as aud, since I don't have any access:

Postman token request:
<img width="610" alt="screenshot 2019-02-18 at 00 11 12" src="https://user-images.githubusercontent.com/36159342/52920881-bc697800-3311-11e9-860b-42a929f04c56.png">

Resulting access token:
```
{
  "jti": "9fefc7c3-6f1b-4c1b-b6d3-aed0fb185cf4",
  "exp": 1550448486,
  "nbf": 0,
  "iat": 1550444886,
  "iss": "http://localhost:8080/auth/realms/master",
  "aud": "account",
  "sub": "00311b0c-4089-436e-8936-c3f34f90453f",
  "typ": "Bearer",
  "azp": "demo-application",
  "auth_time": 0,
  "session_state": "5c2a2bf5-23ea-4918-a6bf-6fcf0dd40722",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "clientId": "demo-application",
  "email_verified": false,
  "clientHost": "172.17.0.1",
  "preferred_username": "service-account-demo-application",
  "clientAddress": "172.17.0.1",
  "email": "service-account-demo-application@placeholder.org"
}
```

This token should be rejected by APICast, but since my client_id is in azp, it would be accepted.

After giving demo-application access to demo-service in Keycloak and rerunning the Postman token request above, the token now looks like this:

```
{
  "jti": "85a0c1b4-b4ea-4626-b82e-db91636904e5",
  "exp": 1550448923,
  "nbf": 0,
  "iat": 1550445323,
  "iss": "http://localhost:8080/auth/realms/master",
  "aud": [
    "demo-service",
    "account"
  ],
  "sub": "00311b0c-4089-436e-8936-c3f34f90453f",
  "typ": "Bearer",
  "azp": "demo-application",
  "auth_time": 0,
  "session_state": "26ec0f13-09c6-4cd0-9f32-cebb761b101b",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "demo-service": {
      "roles": [
        "read"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "clientId": "demo-application",
  "email_verified": false,
  "clientHost": "172.17.0.1",
  "preferred_username": "service-account-demo-application",
  "clientAddress": "172.17.0.1",
  "email": "service-account-demo-application@placeholder.org"
}
```
Now demo-service is in aud, and APICast should accept this token (I did this through roles on demo-service that I assigned to demo-application, but there are probably much better ways to do this in Keycloak. I am a Keycloak novice)

**Comment by mikz** [comment]
Thanks for a very thorough report.

Indeed it looks like we misunderstood the meaning of authorization server and APIcast should not check `aud`. 

It is fine to check just `azp` as the client_id is going to be sent to 3scale backend for verification (basically replacing the aud check).

For pure OIDC environment without 3scale this would be troubling as there would be no protection between services. We will try to address this.

**Comment by magnusvage** [comment]
Great news @mikz !

A further enhancement would be that 3scale checks aud agains an identifier of 3scale itself

`aud=3scale`

Or even better:

`aud=service_system_id`

But that would externalize authorization to the token provider (whoever can get a token with the correct audience, i.e. has access to the service in Keycloak or other OAuth provider would be allowed through 3scale).

I would suggest implementing a validation flow along these lines:
https://auth0.com/docs/api-auth/tutorials/verify-access-token

Except checking the signature, check `exp` and `iss`
Check that `aud` is an identifier of either 3scale or the specific service being called

One could even go one step further, and map each endpoint/mapping rule to a certain claim being present in the token (example: In order to do a GET on /customers, #/scope/claims must contain the string "get.customers"

That way, an incoming token (from any token provider, be it RHSSO, Azure AD or anything else) could completely and finely grained authenticate the calling party and authorize access to the specific endpoint. But then we have moved away from a bugfix and into product enhancement territory.

**Comment by mikz** [comment]
@magnusvage `exp` and `iss`, as well as `nbf`, are already checked.
https://github.com/3scale/apicast/blob/ab4ce9d08759c657944078ba8dbf1216c533c9da/gateway/src/apicast/oauth/oidc.lua#L51-L80

APIcast is not checking `aud` includes 3scale or a service name as it would require setup on the IDP that might be troublesome for some customers. And OIDC in the scope of 3scale is still just an add-on.

For standalone OIDC without 3scale, we definitely will provide some options for checking `aud` claim in the JWT, so customers can configure what should be in the claim.

We have no plan of mapping endpoints/mapping rules to claims (as there is no spec to do that that I'm aware of), but rather go with UMA 2.0 and delegate the access control to the IDP entirely.

**Comment by magnusvage** [comment]
So basically, you intend to only authenticate the calling party using the token, not do any authorization based on the token content (instead, in the 3scale case checking the corresponding application plan for authorization)?

And in standalone mode, leave authorization based on token content up to the backend?

**Comment by mikz** [comment]
When using APIcast with 3scale, we authenticate the token and then call the 3scale backend to verify the access of that client_id. 3scale backend does the authorization and APIcast only verifies the token authenticity (issuer, exp, ...).
To do that we should remove the fallback to `aud` claim when `azp` is not there.

When using APIcast without 3scale (called standalone, that is still in very early work in progress), APIcast would still need to verify the token, but then we would use UMA 2.0 to let the IDP do the authorization or let user define a policy that verifies claims of the token (like `aud`).
This is still work in progress and will be explored in implemented in the coming months.

**Comment by magnusvage** [comment]
@mikz looking foward to seeing that in action.

To make APICast less dependant on 3scale/RHSSO specific things, consider this token issued by Azure AD to my test app:

```
{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/6201d128-1340-4e85-a2d0-ea1900111f99/",
  "iat": 1550573425,
  "nbf": 1550573425,
  "exp": 1550577325,
  "aio": "42JgYPjVIiqSsvc9R8/6mJqD8+aXAQA=",
  "app_displayname": "App Name",
  "appid": "f02da808-6466-488c-b44f-559625234e01",
  "appidacr": "1",
  "idp": "https://sts.windows.net/6201d128-1340-4e85-a2d0-ea1900111f99/",
  "tid": "6201d128-1340-4e85-a2d0-ea1900111f99",
  "uti": "CKKmg_Gc2UWW9VFn6cluAA",
  "ver": "1.0",
  "xms_tcdt": 1450789762
}
```

The `aud` claim here is standard when you don't request any specific access, so we can disregard it (as you are suggesting you should do as well). For this token to be usable as identification in APICast, APICast would have to look at the `appid` claim, since there is no `azp`. Could this be made configurable, to specify which claim in a valid token should be interpreted as the client_id?

**Comment by magnusvage** [comment]
Another issue on the same theme:

If we do not check `aud` on the incoming token in APICast, consider the following two tokens:

<img width="1201" alt="screenshot 2019-02-22 at 08 05 03" src="https://user-images.githubusercontent.com/36159342/53225549-bc9ea600-3678-11e9-8e0d-dbdd2acddf9a.png">

The left one was acquired by the client using the client_credentials flow.
The right one was acquired by using the auhtorization_code flow to log me into the client (which could be a server-side web-app for instance). We use Azure AD as an IdP in RHSSO.

The token to the right would be what I as a user use to access the user-facing part of the app. However, since `azp` in both cases are the client ID, wouldn't the token on the right also allow me (the user) to authenticate as the app towards APICast? Without checking that `aud=apicast` or similar, tokens not meant for use with APICast would be allowed through.

**Comment by mikz** [comment]
Yes, that is expected.

We have Keycloak role check policy to verify the JWT has some properties.
We would like to offer a generic solution for any IDP and just add custom validation to the JWT. I think it will be something I'll be working on pretty soon.

**Comment by magnusvage** [comment]
> Yes, that is expected.

I would like to disagree.

If you use RHSSO to identify your clients, would you like the same clients of yours to be able to impersonate you when talking to an APICast protected API?

**Comment by mikz** [comment]
Those clients would have to also have an application in 3scale with the same client_id. Once there is a corresponding application in 3scale and client in RHSS0, then all the tokens issued for that Client will have access to the API.
If you'd create a Client in RHSSO without the corresponding 3scale application, then it would not be able to access the API.
We suggest using different realms for your API (and a realm per API).

**Comment by magnusvage** [comment]
@mikz I was thinking about users, not clients, sorry for the confusion. So we should not use the same client ID to both authenticate users to access a front-end service and use the same client ID for the front-end service to access back-end services that the front-end service needs? The front-end services should have two different client IDs in two different realms for that purpose?

**Comment by mikz** [comment]
@magnusvage when designing this we focused mainly on server-to-server communication and the Client Credentials authentication flow. 

If you give the user access to the client it would get access to the API, indeed. Can you limit who can get access to the client? 
There is a policy that enforces roles in the JWT, that could be used to limit access of users to the API.
But I don't see why they should have access to the client in the first place, but I might be missing something.

**Comment by magnusvage** [comment]
@mikz consider the follwing.

I am front-end web service running on a server somewhere (not behind 3scale). In order to serve my users, I need to access backend API:s protected by 3scale.

I would use RHSSO to authenticate my users, using my RHSSO client ID and the authorization_code flow. The access token issued by RHSSO in this case would be for the users accessing me, and I would provide the token back to the users so that they can access me.

Now I need to talk to the backend API:s, so I use my client ID again and the client credentials flow to get a token representing me (the front-end web service).

Those are the two tokens in my screenshot above, the left is the server-to-server token I'm going to use to access the backend, the right one is the token that the user is going to use to access me.

That's why the `aud` claim is so important to check, it denotes what access this token was issued for.
As stated in https://tools.ietf.org/html/rfc7519:

Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.

Now this aud value could either be 3scale in general, denoting that the incoming call has access to the API gateway, or it could be the more specific aud value of the API being called. With no aud checks in place, the solution is inherently insecure.

It sounds like, when being designed, the solution did not anticipate RHSSO to be the main source of identity and access management of an entire organization, where 3scale was just one of the consumers of RHSSO, but rather that RHSSO would be a component behind/beneath 3scale, it's only job to provide tokens to identify clients created in RHSSO by 3scale. Would this be correct?

**Comment by magnusvage** [comment]
@mikz I've been thinking about this a lot, and it just dawned on me today that `azp` shouldn't even exist in an access token, at least not according to specs. It is only specified for an ID token, which should never be used to gain access to an API or other protected resource:
https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis#how-not-to-use-tokens

**Comment by kevprice83** [comment]
@magnusvage some of these comments/questions would be better directed to the [keycloak project](https://issues.jboss.org/projects/KEYCLOAK) as we depend on the implementation of OpenID Connect there with our integration. What is returned in the _access_token_ is defined by keycloak for example. I will also try to help answer some of your other questions this week. It will take me some time to discuss some of these points with @mikz and one or both of us will provide some more feedback in the next few days.

**Comment by magnusvage** [comment]
@kevprice83 I was looking for that project but didn't find it, thanks for the link! Don't feel any stress in replying, the world won't end in the next few days (hopefully) :)

**Comment by mikz** [comment]
@magnusvage indeed when designing this we haven't considered the same client would be used for users and accessing the 3scale protected APIs.

However, we can't just use any predefined `aud` and force our clients to use it. It needs to be configurable, opt-in for current customers, opt-out for new ones and it needs documentation how to get a token from the IDP that has the correct `aud`.

For now, the best approach to mitigate this is to use the Keycloak roles policy and force some role to access the 3scale protected API.
Then, when we implement the arbitrary JWT claim check policy, that should be the correct way of using it.

I'm still not sure if this should be opt-in or opt-out for new customers. But with features like https://github.com/3scale/porta/pull/643 we can detect that authorization code flow is active and suggest using correct `aud`.

**Comment by magnusvage** [comment]
@mikz agreed, checking for roles would mitigate it. That will however require manual role administration in Keycloak, correct? Nothing that can be automated given the current integration with Keycloak.

The arbitrary JWT claim check policy sounds promising! Can I read up on what it planned to do somewhere?

**Comment by mikz** [comment]
@magnusvage that would require an extra policy in APIcast: [Keycloak Role Check](https://github.com/3scale/apicast/tree/master/gateway/src/apicast/policy/keycloak_role_check).

There is no definition (yet), but it is something we could start working on soon. The plan would be to try to iterate from the Keycloak Role Check policy.

**Comment by magnusvage** [comment]
@mikz thanks, I'll keep an eye on it!

The Keycloak Role Check policy seems to be suffering of the same type of error, where `{{ jwt.aud }}` is thought to represent the application client, when in a proper setup it should represent the provider client.

**Comment by mikz** [comment]
@magnusvage after thinking this for a while I think we always assumed that the 3scale client (client_id matches the app_id in 3scale) in RHSSO is going to have access to the 3scale APIs. To which APIs is determined by 3scale (by extracting the client_id and calling 3scale backend).
If you want a client that has no access to 3scale, just create a different client for that purpose.

Now with multiple audiences in Keycloak we could start thinking about how you could use this to do an extra layer of security, but still, our recommendation would be to just use a different client for not-3scale purposes. The same RHSSO can still be used as the main source of identity. The users would still be the same. You could just have one client authenticating the web app and its end users and then the web app uses a different client to call the APIs server side.

**Comment by magnusvage** [comment]
@mikz that would definitely mitigate the issue, but it would require all clients being represented by 2 clients in RHSSO. It feels like a sub-optimization, when adding the providers and the proper relationships between consumers and providers to RHSSO could accomplish the same things, make token validation/verification in APICast much more robust, and we would have a One-to-One mapping between real-world applications and clients in RHSSO, which would be a very good thing from a maintainability point of view.

The client having access to 3scale would have to have both Auth code+PKCE and implicit flow disabled, since both of those flows allows me as a user to get a token without the client secret, which would pass the APICast checks as they stand today.

**Comment by mikz** [comment]
@magnusvage how many clients are we talking about here? I imagine all the frontend clients could be represented by one client unless there would be a need to revoke them separately.

I agree that having a way to check the audience is something we should do.
But also that it would add an unnecessary step for most of our customers if it would be required by default. If they'd have to add some Audience Mapper to the client in Keycloak etc.
So I think we would have to stick to expecting that client created by 3scale is going to access 3scale.
And that if you want to disable that in some cases (like when using this client for purposes that do not involve 3scale), then you'd have to remove this audience. I'm not sure how that is done or possible on Keycloak.

I think we will always expect that the client created by 3scale has access to 3scale. Regardless of the flow used to get the access token. Even in auth code flow, it is entirely fine to use 3scale by single page applications. For most cases, the client is expected to access 3scale.

Your case is special because you want to remove that access from the client that already has it.
If you can use some of the Protocol Mappers in Keycloak to remove the `aud` and `azp` then the access token loses the ability to call 3scale.

**Comment by magnusvage** [comment]
@mikz I wouldn't say I want to remove access from a client, just allow it to use its client in RHSSO for things other than accessing 3scale.

By just adding the providers in RHSSO, and doing the `aud` check as prescribed in the RFC https://tools.ietf.org/html/rfc7519#section-4.1.3

Each principal intended to process the JWT MUST identify itself with a value in the audience claim.  If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected.

You could also check the `sub` claim, and use that as the app_id when checking against application plans.

This is in my view the only way forward to get a truly secure OAuth implementation in APICast, without limiting the use of RHSSO to 3scale clients only. However, I do realize that you have a lot of legacy to take into account and that the change I am suggesting is a breaking change of the existing implementation.

**Comment by mikz** [comment]
@magnusvage technically we are checking the `aud` (only when `azp` is not there). And we are relying on its' default value of the `client_id`. 

Would removing `azp` from the client_id check work for you? Then you can issue token with whatever `aud` you want and it would work for 3scale only when its first value is client_id.

**Comment by magnusvage** [comment]
@mikz not really.

`azp` checks should not be done at all, since it is only defined for ID tokens, that should not be used for API access.

`aud` is explicitly defined as: 

> The "aud" (audience) claim identifies the recipients that the JWT is
>    intended for.

Therefore, by checking `aud==3scale_application_id` you are reversing that behaviour, breaking all sorts of things and assumptions in the spec.

I set up an example in an Azure AD tenant on how I think good tokens look like, and I'll try to explain why.

In the tenant we have two clients (Apps in Azure AD lingo), consumerapp and providerapp
The first example is when consumerapp signed me in and requested permission from me to Read and Write stuff in providerapp on my behalf. Let's assume that providerapp is behind 3scale. This is the resulting access token (somewhat redacted):

```
{
  "aud": "api://providerapp",
  "iss": "https://sts.windows.net/TENANTID/",
  "iat": 1552556490,
  "nbf": 1552556490,
  "exp": 1552560390,
  "acr": "1",
  "aio": "ATQAy/8KAAAAZNn/64sQgLVq7kgfGfDOHR0g4ELX+q8JBiclhUIMuCt/jLck4I53jcWmWcj0vSTc",
  "amr": [
    "pwd"
  ],
  "appid": "consumerapp",
  "appidacr": "1",
  "family_name": "Våge",
  "given_name": "Magnus",
  "ipaddr": "MYIPADDRESS",
  "name": "Magnus Våge",
  "oid": "3cdc3e9e-83d9-47c6-a1d4-dce178e289d1",
  "scp": "Read Write",
  "sub": "dRTK7Kus-2MQbunK0z8pCjz4VYxSjj4_10gt444S4Ro",
  "tid": "TENANTID",
  "unique_name": "myemailaddress",
  "upn": "myemailaddress",
  "uti": "uIRMc489G0aIy8lCYokUAA",
  "ver": "1.0"
}
```

The key points:

`"aud": "api://providerapp"`: The token is intended for consumption by the provider app. This can be checked in APICast to match an identifier of the service/API

`"appid": "consumerapp"`: The token was issued to consumerapp. This can be checked in APICast to match an identifer of an application subscribed to this service.

`"scp": "Read Write"`: The access granted by me to consumerapp in providerapp. APICast could ignore these values and let the backend handle fine grained authorization, or I could use the JWT claims check to map these scopes to different endpoints (Does these checks override application plans or does both need to match in order to let a call through APICast?)

The backend would have to act on the `oid` and `sub` claims which identify me as an end-user.

Now switching to the case where consumerapp requests a token to access providerapp using the client credentials flow, i.e. representing itself and not an end-user. The token looks like this (same redactions):

```
{
  "aud": "api://providerapp",
  "iss": "https://sts.windows.net/TENANTID/",
  "iat": 1552557158,
  "nbf": 1552557158,
  "exp": 1552561058,
  "aio": "42JgYOjkev1ZjH1KLCe3EDe31AMfAA==",
  "appid": "consumerapp",
  "appidacr": "1",
  "idp": "https://sts.windows.net/TENANTID/",
  "oid": "aa5beaf8-46e5-43bc-912a-4df0b324652e",
  "sub": "aa5beaf8-46e5-43bc-912a-4df0b324652e",
  "tid": "TENANTID",
  "uti": "n8GImoMDrUSmLSkxaCAXAA",
  "ver": "1.0"
}
```
APICast could make the same checks here, `aud` and `appid` (although appid would be some other claim in the RHSSO case).

Now if I were to request an access token to consumerapp as myself the token would look like this:

```
{
  "aud": "consumerapp",
  "iss": "https://login.microsoftonline.com/TENANTID/v2.0",
  "iat": 1552557776,
  "nbf": 1552557776,
  "exp": 1552561676,
  "aio": "ATQAy/8KAAAAS017Q+7DTwTtbhN8i0Ol9LEeyVbnKPyFdq5SOcQBNdg03xsc1A6y6eaROhIYtZCF",
  "azp": "consumerapp",
  "azpacr": "1",
  "name": "Magnus Våge",
  "oid": "3cdc3e9e-83d9-47c6-a1d4-dce178e289d1",
  "preferred_username": "myemailaddress",
  "scp": "ConsumerAppRead",
  "sub": "_YysjXLB3rWj0Ocg_TDby5l9eVVnunq_fAYxEG1infI",
  "tid": "TENANTID",
  "uti": "36rdMpE0V0KvVYJraBwVAA",
  "ver": "2.0"
}

```
Applying the same checks, `aud` would not match `api://providerapp` and this call could be rejected by APICast.

consumerapp has used the same client in all scenarios, and the tokens issued have all been scoped correctly using the `aud` claim so that all parties involved can make correct decisions based on their contents.

**Comment by MarkCheshire** [comment]
Just one clarification @magnusvage in the earlier reference (https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis#compare-the-tokens), it shows a key difference is that azp is included in access tokens but not in ID tokens.

**Comment by magnusvage** [comment]
@MarkCheshire well, auth0 has the azp in the access token, but in the JWT spec it is only specified for ID tokens. It is a messy world out there, and implementations very rarely follow the specs to the letter.

azp	Authorized party - the party to which the ID Token was issued

References:
https://www.iana.org/assignments/jwt/jwt.xhtml
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

So in an ID token it is an optional claim with a specific meaning.
In an access token it is undefined, but it would make sense to apply the same logic as for the ID token (i.e. the client ID of the client that requested the access token from the authorisation server, either on behalf of itself using a client credentials flow or on behalf of a user using some other flow)

**Comment by MarkCheshire** [comment]
Following a discussion with @nmasse-itix one proposal in the short term is to clarify that within a Keycloak Realm only clients of the the API which are managed by 3scale should be provisioned. They should not be mixed with other types of clients i.e. browser clients or different APIs.

In theory the aud field should include additional checks for the 3scale/API level as well as at the lower granularity of each backend service. However this would come at considerable additional complexity which could not be hidden from the user. Therefore this should be considered as lower priority and if implemented be optional for the API Provider. Note that without this the above point about the Realm is especially important.

Does this make sense @mikz ?

**Comment by mikz** [comment]
@magnusvage ok, here is our proposal for the next release.

I'd like to reiterate that it is not a security issue, as the 3scale backend authorizes the application before sending it upstream. And you are using a Client that is supposed to have access to 3scale regardless of what authentication flow you use. You want to further restrict it and reject that access in some cases. To make that happen we would:

1. Remove checking `aud` for the app_id.
2. Make `azp` claim configurable (where we expect the app_id), so we can be compatible with other IDPs. I don't see any 
3. Introduce a policy for arbitrary JWT claim verification. You'll be able to require whatever `aud` claim you want (and even use liquid like in the other policies) (https://github.com/3scale/APIcast/issues/995).

In case of Keycloak the Access Token shares a lot with the ID Token. We are leveraging this to get the client_id. We don't really have any other means to get the client_id than from `azp` claim. So for Keycloak, that that won't change. But I'll be able to configure from where to take the client_id if you are using different IDP.

Does that sound good enough?

**Comment by magnusvage** [comment]
Hi!

@mikz Yes, but I would like to point out that without a mandatory `aud` check on a service level 3scale services that do not implement these checks on its own will still be vulnerable to the Different Recipient substition attack as described here: https://auth0.com/blog/a-look-at-the-latest-draft-for-jwt-bcp/#pitfalls-and-common-attacks

Tokens MUST contain information of the intended consumer of the token. If service A and service B are both behind 3scale, and user A calls service A, service A could reuse the token it received from user A to consume service B as user A unless these claims are in place and checked (since the token that user A has is valid for both service A and service B in 3scale).

With the changes you suggest, we could mitigate this by customising each service in 3scale with the arbitrary JWT validation, and also maintaining all services/providers in Keycloak. This should be an out-ot-the-box behaviour.

**Comment by mikz** [comment]
@magnusvage Given Client abc on Service A and User A and Client def on Service B. A token of client abc will be valid only on Service A and token of Client dev only on Service B.
The client id is going to be verified against 3scale backend and verify that the client has access to the service. We do not rely on audience, but on the client_id that gets verified by 3scale backend.

**Comment by magnusvage** [comment]
@mikz agreed, but what if you in the future decide to allow the client to use the same credentials to authenticate against multiple services? It would be nice to not have to manage 15 sets of credentials if I need to access 15 different APIs thropugh 3scale.

Also, your scenario means that there must be no way to call the backend directly, it must only accept calls routed through 3scale. That might not be a desirable setup in all use cases.

**Comment by mikz** [comment]
@magnusvage In our data model an Application (Client) belongs to a Service, so it can never access multiple services. API-as-a-product that allows you to access many services with one Application (Client) will be likely desinged by extra scopes / permissions within one API and rely on 3scale metrics.

Yes, to protect your API you need to expose it *only* though 3scale. Otherwise anyone can access it without authentication.

**Comment by davidor** [comment]
The 3 things that @mikz  proposed in https://github.com/3scale/APIcast/issues/988#issuecomment-477972776 have already been addressed:
#1007 
#1034 
#1070 

I'll close this.
