### ISSUE TITLE
TLS Termination Policy

### ISSUE THREAD

**Issue by mikz** [3scale/APIcast#999]
Right now APIcast can serve just one TLS certificate for all services (configured by ENV variable). We need a way to have the ability to do this by a policy per service (using ssl_certificate phase).

This policy should be able to offer TLS certificate from various sources: 

* stored in the policy configuration
* stored on the filesystem

But it also could be able to request a certificate from different services like:

* SPIRE/SPIFFE
* ACME (LetsEncrypt) (https://github.com/GUI/lua-resty-auto-ssl)

**Comment by eloycoto** [comment]
closed by https://github.com/3scale/APIcast/tree/master/gateway/src/apicast/policy/tls
